require 'commands.chat_commands'
require 'commands.difficulty_voting_commands'
require 'commands.instant_map_reset'
require 'commands.current_map_seed'
require 'commands.suspend'
require 'commands.where'
