-- changelog tab -- 
local Tabs = require 'comfy_panel.main'

local function add_changelog(player, element)
	local changelog_scrollpanel = element.add { type = "scroll-pane", name = "scroll_pane", direction = "vertical", horizontal_scroll_policy = "never", vertical_scroll_policy = "auto"}
	changelog_scrollpanel.style.maximal_height = 530
	
	local changelog_change = {}
        table.insert(changelog_change,"2023-10-19")
        table.insert(changelog_change,"perf : Ignore damage events for non-biters and increase refresh delay for healthbar of bosses")
        table.insert(changelog_change,"cogito123")
        table.insert(changelog_change,"2023-10-19")
        table.insert(changelog_change,"perf : Increase refresh threat min delay and optim on code")
        table.insert(changelog_change,"XVhc6A")
        table.insert(changelog_change,"2023-10-19")
        table.insert(changelog_change,"perf : biter terrain tiles optim")
        table.insert(changelog_change,"cogito123")
        table.insert(changelog_change,"2023-10-19")
        table.insert(changelog_change,"New feature : suspend player")
        table.insert(changelog_change,"Ragnarok77")
        table.insert(changelog_change,"2023-10-19")
        table.insert(changelog_change,"info json file")
        table.insert(changelog_change,"XVhc6A")
        table.insert(changelog_change,"2013-10-19")
        table.insert(changelog_change,"Add instant map reset command with optional seed argument")
        table.insert(changelog_change,"XVhc6A")
        table.insert(changelog_change,"2023-10-19")
        table.insert(changelog_change,"Reveal map at start")
        table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2023-10-19")
	table.insert(changelog_change,"Special game Mixed ore map")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2023-10-19")
	table.insert(changelog_change,"bugfix : NaN propagation in strike code generating desynch")
	table.insert(changelog_change,"amannm")
	table.insert(changelog_change,"2023-10-07")
	table.insert(changelog_change,"Update changelog script to have it ordered")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2023-10-03")
	table.insert(changelog_change,"Introduce map reroll")
	table.insert(changelog_change,"PlayerNoon")
	table.insert(changelog_change,"2023-10-03")
	table.insert(changelog_change,"Special game disable sciences from sending")
	table.insert(changelog_change,"PlayerNoon")
	table.insert(changelog_change,"2023-09-29")
	table.insert(changelog_change,"Improved /inventory performance")
	table.insert(changelog_change,"penguinencounter")
	table.insert(changelog_change,"2023-07-20")
	table.insert(changelog_change,"Allow change_active_item_group_for_filters for spectators")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2023-07-14")
	table.insert(changelog_change,"Allows group name and description to include spaces and punctuation characters")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2023-07-14")
	table.insert(changelog_change,"Set permission selected_tab_changed to true even when frozen so ui not broken anymore for special/groups")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2023-07-13")
	table.insert(changelog_change,"Remove Unused Module and terrain code")
	table.insert(changelog_change,"XVhc6A")
	table.insert(changelog_change,"2023-07-13")
	table.insert(changelog_change,"Clear area of rocks for placing silo's turret pair (redo)")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2023-06-29")
	table.insert(changelog_change,"feat: add send to server in admin gui")
	table.insert(changelog_change,"gabrielchl")
	table.insert(changelog_change,"2023-06-17")
	table.insert(changelog_change,"Refined concrete within starting area walls")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2023-06-17")
	table.insert(changelog_change,"Bugfix special-events : Prevent bots from placing disabled entities")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2023-05-07")
	table.insert(changelog_change,"refactor out existing AI functions cleanly into 'Strikes' and 'Targets'")
	table.insert(changelog_change,"amannm")
	table.insert(changelog_change,"2023-01-29")
	table.insert(changelog_change,"fix autounlock uranium ammo after sulfur reaserch")
	table.insert(changelog_change,"PlayerNoon")
	table.insert(changelog_change,"2023-01-27")
	table.insert(changelog_change,"Special event shared evo and throws")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2023-01-26")
	table.insert(changelog_change,"Bugfix to avoid spam of error in log when decon")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2023-01-26")
	table.insert(changelog_change,"Do not allow players to create a new group with the name of an existing group")
	table.insert(changelog_change,"voski")
	table.insert(changelog_change,"2023-01-26")
	table.insert(changelog_change,"feat(gui): show game speed next to game time")
	table.insert(changelog_change,"gabrielchl")
	table.insert(changelog_change,"2023-01-26")
	table.insert(changelog_change,"fix team name on biters spotted")
	table.insert(changelog_change,"PlayerNoon")
	table.insert(changelog_change,"2023-01-26")
	table.insert(changelog_change,"difficulty_vote: prevent voting same difficulty.")
	table.insert(changelog_change,"PlayerNoon")
	table.insert(changelog_change,"2022-12-18")
	table.insert(changelog_change,"Change river function")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2022-12-18")
	table.insert(changelog_change,"Add New Year Island decorations")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2022-12-18")
	table.insert(changelog_change,"Fix Limited lives desync")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2022-12-18")
	table.insert(changelog_change,"Perf: Improve river check function")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2022-11-22")
	table.insert(changelog_change,"Replaced element_style() with gui_style()")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-11-22")
	table.insert(changelog_change,"New feature : show amount of votes of diff in gui")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-11-22")
	table.insert(changelog_change,"Special game: Limited lives")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2022-11-18")
	table.insert(changelog_change,"Enable profiler")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-10-25")
	table.insert(changelog_change,"French translation of welcome message")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-09-12")
	table.insert(changelog_change,"Develop to master")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-09-11")
	table.insert(changelog_change,"Dev backport")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-09-11")
	table.insert(changelog_change,"Fix threat boss issue going negative too often (waves were oversized) and frozen boss bug and added boss announce")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-08-27")
	table.insert(changelog_change,"New histories")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-08-06")
	table.insert(changelog_change,"Added path to errors from event_core")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-08-06")
	table.insert(changelog_change,"Show big threat value with k or m at end of text")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-08-06")
	table.insert(changelog_change,"Enabled editor and config in spectator")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-08-05")
	table.insert(changelog_change,"Fix spectator in vehicle")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2022-08-05")
	table.insert(changelog_change,"Fix ghost rotation by spectator")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2022-08-05")
	table.insert(changelog_change,"Ura ammo and kovarex researched when ura processing is researched, same for gate with wall")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-07-30")
	table.insert(changelog_change,"Prevent pathfinder crossing river(made by developer-8, not Ragnarok77)")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-07-30")
	table.insert(changelog_change,"perf: Small improvements to biter reanimation logic")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2022-07-30")
	table.insert(changelog_change,"Disabled polls")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-06-25")
	table.insert(changelog_change,"Perf : No find entities used when defense are built are far from nest")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-06-25")
	table.insert(changelog_change,"Added mixed send functionality")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-06-25")
	table.insert(changelog_change,"Anti afk system")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-06-25")
	table.insert(changelog_change,"Global speaker won't nuke speakers in jail and jail speaker heard by all forces")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-06-09")
	table.insert(changelog_change,"Implementation of boss")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-06-09")
	table.insert(changelog_change,"Backport")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2022-05-31")
	table.insert(changelog_change,"added launch silo sentence in welcome message")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-05-31")
	table.insert(changelog_change,"Dev backport")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2022-05-31")
	table.insert(changelog_change,"Increase ura frequency by 10%, copper frequency by 15%")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-05-31")
	table.insert(changelog_change,"Added uranium ammo research researched by default")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-05-15")
	table.insert(changelog_change,"Fix messing research queue exploit in jail")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-05-15")
	table.insert(changelog_change,"Special games gui tweaks")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-05-15")
	table.insert(changelog_change,"Removed auto research of silo")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-05-15")
	table.insert(changelog_change,"Disabled manual rocket launch")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-05-15")
	table.insert(changelog_change,"Fixed exploit landfill enemy side and no decon on enemy side")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-05-12")
	table.insert(changelog_change,"Changed yellow sci mutagen from 1200 to 1600")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-05-06")
	table.insert(changelog_change,"Revert 'Admin panel redo'")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-04-30")
	table.insert(changelog_change,"Admin panel redo")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-04-22")
	table.insert(changelog_change,"Welcome message")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2022-04-20")
	table.insert(changelog_change,"Special game disabled research")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-04-20")
	table.insert(changelog_change,"Added auto-shouting after game ending")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-04-20")
	table.insert(changelog_change,"Changed jail_song variables to local")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-04-20")
	table.insert(changelog_change,"Special game: Disabled entities")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-04-13")
	table.insert(changelog_change,"Fix an exploit with landfill")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2022-04-13")
	table.insert(changelog_change,"Change GitHub link to this GitHub")
	table.insert(changelog_change,"gsquaredxc")
	table.insert(changelog_change,"2022-04-13")
	table.insert(changelog_change,"Fixed double printing shouts for admins")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2022-02-01")
	table.insert(changelog_change,"Revert 'Add holiday decorations to the island'")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2021-12-28")
	table.insert(changelog_change,"Cancel crafting queue when going to spectate")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-28")
	table.insert(changelog_change,"Renamed autotag to just East or West for shorter name instead")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-25")
	table.insert(changelog_change,"holidays")
	table.insert(changelog_change,"1pulse")
	table.insert(changelog_change,"2021-12-25")
	table.insert(changelog_change,"Create troll song at map init in jail")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-25")
	table.insert(changelog_change,"Add holiday decorations to the island")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2021-12-19")
	table.insert(changelog_change,"Mirror decoratives to south")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2021-12-17")
	table.insert(changelog_change,"Auto tagging outpost")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-15")
	table.insert(changelog_change,"Increased copper and stone size by 10%")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-15")
	table.insert(changelog_change,"Add changelog tab")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-15")
	table.insert(changelog_change,"Set path_finder settings")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-12-15")
	table.insert(changelog_change,"Add more threat to compensate revive")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-12-15")
	table.insert(changelog_change,"Clear clipboard on game join")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-12-12")
	table.insert(changelog_change,"Update/prevent landfilling by untrusted user")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-12")
	table.insert(changelog_change,"Removed trust check on clear-corpses command")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-12")
	table.insert(changelog_change,"Fix silo grief (mirroring)")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-09")
	table.insert(changelog_change,"fix antigrief inconsistency")
	table.insert(changelog_change,"XVhc6A")
	table.insert(changelog_change,"2021-12-09")
	table.insert(changelog_change,"Limited threshold of biters reviving to 90% chance")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-09")
	table.insert(changelog_change,"Do not allow ghosts on enemy side")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2021-12-09")
	table.insert(changelog_change,"Fix difficulty GUI lag spikes")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-12-09")
	table.insert(changelog_change,"Added infinite spy when white science is thrown")
	table.insert(changelog_change,"Ragnarok77")
	table.insert(changelog_change,"2021-12-06")
	table.insert(changelog_change,"Added special_games system")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-12-06")
	table.insert(changelog_change,"Improve biter performance")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-11-25")
	table.insert(changelog_change,"Remove vehicle from silo")
	table.insert(changelog_change,"developer-8")
	table.insert(changelog_change,"2021-11-21")
	table.insert(changelog_change,"Ban improvements")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-11-21")
	table.insert(changelog_change,"First join gui minor tweaks")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-11-19")
	table.insert(changelog_change,"Quick and dirty way to fix desync")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-11-10")
	table.insert(changelog_change,"Improved readme")
	table.insert(changelog_change,"Tomab")
	table.insert(changelog_change,"2021-11-08")
	table.insert(changelog_change,"Change text warning to accurately reflect mechanics")
	table.insert(changelog_change,"Tomab")
	table.insert(changelog_change,"2021-10-30")
	table.insert(changelog_change,"shout-fix: fix shout logging so that non admin shouts get logged too")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-10-30")
	table.insert(changelog_change,"mutes - make mute great again")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-10-11")
	table.insert(changelog_change,"Top gui visual cleanup")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-10-11")
	table.insert(changelog_change,"Add join_random_button")
	table.insert(changelog_change,"TheBigZet")
	table.insert(changelog_change,"2021-09-19")
	table.insert(changelog_change,"Print msg to admin upon offshore pump mining")
	table.insert(changelog_change,"gabrielchl")
	table.insert(changelog_change,"2021-09-19")
	table.insert(changelog_change,"spying-fix: if you've chosen a team, remove space sci button")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-09-14")
	table.insert(changelog_change,"discord-log-shout: log shout messages to discord")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-08-31")
	table.insert(changelog_change,"we-survivor: automate sending ppl to spec. Make the delay to return to team configurable")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-08-13")
	table.insert(changelog_change,"Fix evo reset when admins change difficulty")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-08-13")
	table.insert(changelog_change,"Add comment to clear_copy_history")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-07-24")
	table.insert(changelog_change,"clear-bp-history: overwrite copy history with miner")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-07-18")
	table.insert(changelog_change,"inverse-game: disable friendly_fire")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-07-17")
	table.insert(changelog_change,"inverse-game")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-06-27")
	table.insert(changelog_change,"Pixie dust")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-06-20")
	table.insert(changelog_change,"Remove all turrets from target pool")
	table.insert(changelog_change,"cogito123")
	table.insert(changelog_change,"2021-06-16")
	table.insert(changelog_change,"Fix truncated ores around spawn area")
	table.insert(changelog_change,"cogito123")
	table.insert(changelog_change,"2021-06-08")
	table.insert(changelog_change,"Add support for configurable spawn area ore patches")
	table.insert(changelog_change,"cogito123")
	table.insert(changelog_change,"2021-06-08")
	table.insert(changelog_change,"2nd attempt at increasing difficulty")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-06-05")
	table.insert(changelog_change,"Rework unit reanimation system")
	table.insert(changelog_change,"cogito123")
	table.insert(changelog_change,"2021-05-23")
	table.insert(changelog_change,"Revert 'few commands for WE. no need revert after event end. (i think so :D )'")
	table.insert(changelog_change,"1pulse")
	table.insert(changelog_change,"2021-05-23")
	table.insert(changelog_change,"few commands for WE. no need revert after event end. (i think so :D )")
	table.insert(changelog_change,"ghost")
	table.insert(changelog_change,"2021-05-23")
	table.insert(changelog_change,"Biters bugfixes")
	table.insert(changelog_change,"cogito123")
	table.insert(changelog_change,"2021-05-22")
	table.insert(changelog_change,"Remove additional teleport during game over phase")
	table.insert(changelog_change,"cogito123")
	table.insert(changelog_change,"2021-05-20")
	table.insert(changelog_change,"Force chunk replication into lockstep")
	table.insert(changelog_change,"cogito123")
	table.insert(changelog_change,"2021-05-17")
	table.insert(changelog_change,"Improvement to map generation performance")
	table.insert(changelog_change,"cogito123")
	table.insert(changelog_change,"2021-05-15")
	table.insert(changelog_change,"Always use a standard team name in post-game discord message (and more QoL stuff)")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-05-15")
	table.insert(changelog_change,"Add two wood to inventory like in vanilla")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-05-09")
	table.insert(changelog_change,"More improvements 1")
	table.insert(changelog_change,"1pulse")
	table.insert(changelog_change,"2021-05-09")
	table.insert(changelog_change,"Revert #140")
	table.insert(changelog_change,"Hornwitser")
	table.insert(changelog_change,"2021-05-09")
	table.insert(changelog_change,"Laser and mutagen suggestions")
	table.insert(changelog_change,"1pulse")
	table.insert(changelog_change,"2021-05-01")
	table.insert(changelog_change,"Update feeding.lua - buff endgame biters")
	table.insert(changelog_change,"derkachdaniil")
	table.insert(changelog_change,"2021-04-26")
	table.insert(changelog_change,"Balance update 1")
	table.insert(changelog_change,"1pulse")
	table.insert(changelog_change,"2021-04-24")
	table.insert(changelog_change,"fix revive biters")
	table.insert(changelog_change,"ghost")
	table.insert(changelog_change,"2021-04-24")
	table.insert(changelog_change,"Fix revive buff not applying")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-03-23")
	table.insert(changelog_change,"update-discord-link: update chatbot.lua with correct discord link,")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-03-23")
	table.insert(changelog_change,"update-discord-link: free biter battles")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-03-18")
	table.insert(changelog_change,"Revert 'Revert 'Disabled mines temporarily until better fix is found''")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2021-03-16")
	table.insert(changelog_change,"Revert 'Disabled mines temporarily until better fix is found'")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2021-03-15")
	table.insert(changelog_change,"Revert 'Difficulty voting by average'")
	table.insert(changelog_change,"guppyfaced")
	table.insert(changelog_change,"2021-03-15")
	table.insert(changelog_change,"Fix ai pathfinding v2")
	table.insert(changelog_change,"guppyfaced")
	table.insert(changelog_change,"2021-03-15")
	table.insert(changelog_change,"flamer upgrades buff")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-03-15")
	table.insert(changelog_change,"Limit mines")
	table.insert(changelog_change,"derkachdaniil")
	table.insert(changelog_change,"2021-03-15")
	table.insert(changelog_change,"Difficulty voting by average")
	table.insert(changelog_change,"guymaor86")
	table.insert(changelog_change,"2021-03-14")
	table.insert(changelog_change,"fix difficulty reversion glitch for 480 min games")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-03-12")
	table.insert(changelog_change,"stone copper buff")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-03-12")
	table.insert(changelog_change,"DashCee: Reducing DashCee's PR. Removing unused maps")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-03-07")
	table.insert(changelog_change,"Laser Buff")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-03-07")
	table.insert(changelog_change,"changeable projectile_damage_upgrade")
	table.insert(changelog_change,"derkachdaniil")
	table.insert(changelog_change,"2021-03-07")
	table.insert(changelog_change,"damage updates customizable")
	table.insert(changelog_change,"derkachdaniil")
	table.insert(changelog_change,"2021-03-06")
	table.insert(changelog_change,"Disabled mines temporarily until better fix is found")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2021-03-06")
	table.insert(changelog_change,"Reduced Voting Options")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-03-06")
	table.insert(changelog_change,"Update Peace Periods (slower increase)")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-03-06")
	table.insert(changelog_change,"Add Peace Periods")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-03-06")
	table.insert(changelog_change,"Reduced Difficulty for Choices below Normal")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-03-06")
	table.insert(changelog_change,"Update ai.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-03-06")
	table.insert(changelog_change,"Disabled Science Feeding before Voting Ends")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-03-06")
	table.insert(changelog_change,"Update difficulty_vote.lua ????")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-03-01")
	table.insert(changelog_change,"Updated Readme to include TOC and new URL to git repo")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2021-02-26")
	table.insert(changelog_change,"Fixed a bug that displays the seconds as a decimal")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2021-02-26")
	table.insert(changelog_change,"Revert 'Improve biter pathfinding'")
	table.insert(changelog_change,"guymaor86")
	table.insert(changelog_change,"2021-02-25")
	table.insert(changelog_change,"Improve biter pathfinding")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-02-17")
	table.insert(changelog_change,"torunament-feb21: removing free silo")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-01-26")
	table.insert(changelog_change,"Fix lag in long games")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-01-25")
	table.insert(changelog_change,"Updated endgame message upon Raven's request")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2021-01-25")
	table.insert(changelog_change,"Update tables.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-25")
	table.insert(changelog_change,"Update init.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-25")
	table.insert(changelog_change,"Removed update_difficulty() in ai.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-25")
	table.insert(changelog_change,"Revert Blocking Science Sent before Voting Ends")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-25")
	table.insert(changelog_change,"Update init.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-25")
	table.insert(changelog_change,"Update ai.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-25")
	table.insert(changelog_change,"Update main.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-23")
	table.insert(changelog_change,"Fix mines")
	table.insert(changelog_change,"derkachdaniil")
	table.insert(changelog_change,"2021-01-18")
	table.insert(changelog_change,"Update PR template")
	table.insert(changelog_change,"guymaor86")
	table.insert(changelog_change,"2021-01-17")
	table.insert(changelog_change,"Fixup silo research changes")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-01-16")
	table.insert(changelog_change,"Revert 'Update tables.lua'")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-16")
	table.insert(changelog_change,"Revert 'Update tables.lua'")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-16")
	table.insert(changelog_change,"Revert 'Update tables.lua'")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-16")
	table.insert(changelog_change,"Revert 'Update tables.lua'")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-16")
	table.insert(changelog_change,"Chat cmd updates")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2021-01-15")
	table.insert(changelog_change,"Additional commands")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-01-15")
	table.insert(changelog_change,"tournament mode - admin can send message as a spectator")
	table.insert(changelog_change,"guymaor86")
	table.insert(changelog_change,"2021-01-15")
	table.insert(changelog_change,"vote fix. now will round to higher difficulty.")
	table.insert(changelog_change,"ghost")
	table.insert(changelog_change,"2021-01-15")
	table.insert(changelog_change,"Added 10 burner miner drills when player spawns")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2021-01-15")
	table.insert(changelog_change,"Added 2 turrets around silo")
	table.insert(changelog_change,"guymaor86")
	table.insert(changelog_change,"2021-01-15")
	table.insert(changelog_change,"Refactor free silo")
	table.insert(changelog_change,"AwesomePatrol")
	table.insert(changelog_change,"2021-01-15")
	table.insert(changelog_change,"Update tables.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-15")
	table.insert(changelog_change,"Update tables.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-13")
	table.insert(changelog_change,"difficulty-votes: clear vote table on revote")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2021-01-13")
	table.insert(changelog_change,"Update tables.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-12")
	table.insert(changelog_change,"Update tables.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2021-01-11")
	table.insert(changelog_change,"Notifies both teams when a new level of biter spawns")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2021-01-11")
	table.insert(changelog_change,"Added options to send more fish at a time, updated tooltip")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2020-12-29")
	table.insert(changelog_change,"Updated discord link to never expire and put at top of info")
	table.insert(changelog_change,"thePiedPiper13")
	table.insert(changelog_change,"2020-12-27")
	table.insert(changelog_change,"Centralize ammo modifier values")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-27")
	table.insert(changelog_change,"Fixed typos & unused variables")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2020-12-27")
	table.insert(changelog_change,"Updated Readme File with formatting, added Testing Instructions & modified text on PR's")
	table.insert(changelog_change,"kajendra")
	table.insert(changelog_change,"2020-12-27")
	table.insert(changelog_change,"Pull request template")
	table.insert(changelog_change,"guymaor86")
	table.insert(changelog_change,"2020-12-27")
	table.insert(changelog_change,"Update init.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-12-27")
	table.insert(changelog_change,"Prevent bots from tiling")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-22")
	table.insert(changelog_change,"Difficulty vote commands")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-22")
	table.insert(changelog_change,"Update init.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-12-22")
	table.insert(changelog_change,"Update difficulty_vote.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-12-22")
	table.insert(changelog_change,"Update tables.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-12-22")
	table.insert(changelog_change,"Update difficulty_vote.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-12-21")
	table.insert(changelog_change,"issue-36: chatbot - on_console_chat - remove get server time as it causes problems")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-20")
	table.insert(changelog_change,"Update ai.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-12-20")
	table.insert(changelog_change,"put back normal values for nades")
	table.insert(changelog_change,"1pulse")
	table.insert(changelog_change,"2020-12-20")
	table.insert(changelog_change,"bb: adding evo threat and player list to end of game messages")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-20")
	table.insert(changelog_change,"Make river wider against rocket launchers")
	table.insert(changelog_change,"guymaor86")
	table.insert(changelog_change,"2020-12-18")
	table.insert(changelog_change,"Update tables.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-12-17")
	table.insert(changelog_change,"biter battle: send chat to discord even during tournament")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-17")
	table.insert(changelog_change,"mirror map-not mirror reverse")
	table.insert(changelog_change,"guymaor86")
	table.insert(changelog_change,"2020-12-17")
	table.insert(changelog_change,"biter-battles: mvp stats only get sent once")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-17")
	table.insert(changelog_change,"New guide in readme")
	table.insert(changelog_change,"guymaor86")
	table.insert(changelog_change,"2020-12-15")
	table.insert(changelog_change,"add mysticamber link for discord bot")
	table.insert(changelog_change,"1pulse")
	table.insert(changelog_change,"2020-12-14")
	table.insert(changelog_change,"Update init.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-12-14")
	table.insert(changelog_change,"File text updates")
	table.insert(changelog_change,"DashCee")
	table.insert(changelog_change,"2020-12-11")
	table.insert(changelog_change,"biter-battles: adding north-chat and south-chat commands")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-11")
	table.insert(changelog_change,"Contributing to repo")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-11")
	table.insert(changelog_change,"Updated Biter battles map info (?) description to include 2 guides and the discord server links")
	table.insert(changelog_change,"thePiedPiper13")
	table.insert(changelog_change,"2020-12-10")
	table.insert(changelog_change,"Updating readme")
	table.insert(changelog_change,"DashCee")
	table.insert(changelog_change,"2020-12-10")
	table.insert(changelog_change,"default bbv2")
	table.insert(changelog_change,"1pulse")
	table.insert(changelog_change,"2020-12-10")
	table.insert(changelog_change,"Update control.lua")
	table.insert(changelog_change,"1pulse")
	table.insert(changelog_change,"2020-12-10")
	table.insert(changelog_change,"Updating the oil yield value from 0.27 to 0.5. ")
	table.insert(changelog_change,"DashCee")
	table.insert(changelog_change,"2020-12-10")
	table.insert(changelog_change,"Update init.lua")
	table.insert(changelog_change,"thePiedPiper13")
	table.insert(changelog_change,"2020-12-10")
	table.insert(changelog_change,"change vote system from average to median")
	table.insert(changelog_change,"ghost")
	table.insert(changelog_change,"2020-12-10")
	table.insert(changelog_change,"Compress difficulty values upwards")
	table.insert(changelog_change,"DashCee")
	table.insert(changelog_change,"2020-12-10")
	table.insert(changelog_change,"mixed ore patches: adding multiplier")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-10")
	table.insert(changelog_change,"Chat")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-10")
	table.insert(changelog_change,"biter-battles: adding option to only send msg to a specific team as a spectator")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-12-07")
	table.insert(changelog_change,"biter-battles: difficulty vote - removing hard coded 7 in difficulties")
	table.insert(changelog_change,"mysticamber")
	table.insert(changelog_change,"2020-11-28")
	table.insert(changelog_change,"Update init.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-11-28")
	table.insert(changelog_change,"Update terrain.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-11-28")
	table.insert(changelog_change,"Update difficulty_vote.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-11-28")
	table.insert(changelog_change,"Update main.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-11-28")
	table.insert(changelog_change,"Update init.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-11-27")
	table.insert(changelog_change,"Update functions.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-11-27")
	table.insert(changelog_change,"Update tables.lua")
	table.insert(changelog_change,"St4telyRaven")
	table.insert(changelog_change,"2020-11-27")
	table.insert(changelog_change,"Update ai.lua")
	table.insert(changelog_change,"St4telyRaven")
	
	local t = changelog_scrollpanel.add { type = "table", name = "changelog_header_table", column_count = 3 }
	local column_widths = {tonumber(115), tonumber(435), tonumber(230)}
	local headers = {
		[1] = "Date",
		[2] = "Change",
		[3] = "Author",
	}
	for _, w in ipairs(column_widths) do
	local label = t.add { type = "label", caption = headers[_] }
	label.style.minimal_width = w
	label.style.maximal_width = w
	label.style.font = "default-bold"
	label.style.font_color = { r=0.98, g=0.66, b=0.22 }
	end
	changelog_panel_table = changelog_scrollpanel.add { type = "table", column_count = 3 }
	if changelog_change then
		for i = 1, #changelog_change, 3 do
			local label = changelog_panel_table.add { type = "label", name = "changelog_date" .. i, caption = changelog_change[i] }
			label.style.minimal_width = column_widths[1]
			label.style.maximal_width = column_widths[1]
			local label = changelog_panel_table.add { type = "label", name = "changelog_change" .. i, caption = changelog_change[i+1] }
			label.style.minimal_width = column_widths[2]
			label.style.maximal_width = column_widths[2]
			local label = changelog_panel_table.add { type = "label", name = "changelog_author" .. i, caption = changelog_change[i+2] }
			label.style.minimal_width = column_widths[3]
			label.style.maximal_width = column_widths[3]
		end
	end
end

function comfy_panel_get_active_frame(player)
	if not player.gui.left.comfy_panel then return false end
	if not player.gui.left.comfy_panel.tabbed_pane.selected_tab_index then return player.gui.left.comfy_panel.tabbed_pane.tabs[1].content end
	return player.gui.left.comfy_panel.tabbed_pane.tabs[player.gui.left.comfy_panel.tabbed_pane.selected_tab_index].content 
end

local build_config_gui = (function (player, frame)		
	local frame_changelog = comfy_panel_get_active_frame(player)
	if not frame_changelog then
		return
	end
	frame_changelog.clear()
	add_changelog(player, frame_changelog)
end)

comfy_panel_tabs["Changelog"] = {gui = build_config_gui, admin = false}
