-- changelogs tab -- 
local Tabs = require 'comfy_panel.main'

local function add_changelogs(player, element)
	local changelogs_scrollpanel = element.add { type = "scroll-pane", name = "scroll_pane", direction = "vertical", horizontal_scroll_policy = "never", vertical_scroll_policy = "auto"}
	changelogs_scrollpanel.style.maximal_height = 530
	
	local changelogs_change = {}
	table.insert(changelogs_change,"2021-12-09")
	table.insert(changelogs_change,"Do not allow ghosts on enemy side")
	table.insert(changelogs_change,"developer-8")
	table.insert(changelogs_change,"2021-12-09")
	table.insert(changelogs_change,"Limited threshold of biters reviving to 90% chance")
	table.insert(changelogs_change,"Ragnarok77-factorio")
	table.insert(changelogs_change,"2021-12-09")
	table.insert(changelogs_change,"Added infinite spy when white science is thrown")
	table.insert(changelogs_change,"Ragnarok77-factorio")
	table.insert(changelogs_change,"2021-12-09")
	table.insert(changelogs_change,"Fix difficulty GUI lag spikes")
	table.insert(changelogs_change,"AwesomePatrol")
	table.insert(changelogs_change,"2021-12-06")
	table.insert(changelogs_change,"Improve biter performance")
	table.insert(changelogs_change,"AwesomePatrol")
	table.insert(changelogs_change,"2021-12-09")
	table.insert(changelogs_change,"fix antigrief inconsistency")
	table.insert(changelogs_change,"XVhc6A")
	table.insert(changelogs_change,"2021-11-19")
	table.insert(changelogs_change,"Quick and dirty way to fix desync")
	table.insert(changelogs_change,"TheBigZet")
	table.insert(changelogs_change,"2021-12-06")
	table.insert(changelogs_change,"Added special_games system")
	table.insert(changelogs_change,"TheBigZet")
	table.insert(changelogs_change,"2021-11-08")
	table.insert(changelogs_change,"Change text warning to accurately reflect mechanics")
	table.insert(changelogs_change,"Tomab")
	table.insert(changelogs_change,"2021-11-10")
	table.insert(changelogs_change,"Improved readme")
	table.insert(changelogs_change,"Tomab")
	table.insert(changelogs_change,"2021-11-21")
	table.insert(changelogs_change,"Ban improvements")
	table.insert(changelogs_change,"TheBigZet")
	table.insert(changelogs_change,"2021-10-30")
	table.insert(changelogs_change,"mutes - make mute great again")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-10-30")
	table.insert(changelogs_change,"shout-fix: fix shout logging so that non admin shouts get logged too")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-11-25")
	table.insert(changelogs_change,"Remove vehicle from silo")
	table.insert(changelogs_change,"developer-8")
	table.insert(changelogs_change,"2021-11-21")
	table.insert(changelogs_change,"First join gui minor tweaks")
	table.insert(changelogs_change,"TheBigZet")
	table.insert(changelogs_change,"2021-10-11")
	table.insert(changelogs_change,"Add join_random_button")
	table.insert(changelogs_change,"TheBigZet")
	table.insert(changelogs_change,"2021-10-11")
	table.insert(changelogs_change,"Top gui visual cleanup")
	table.insert(changelogs_change,"TheBigZet")
	table.insert(changelogs_change,"2021-09-19")
	table.insert(changelogs_change,"spying-fix: if you've chosen a team, remove space sci button")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-09-19")
	table.insert(changelogs_change,"Print msg to admin upon offshore pump mining")
	table.insert(changelogs_change,"gabrielchl")
	table.insert(changelogs_change,"2021-08-31")
	table.insert(changelogs_change,"we-survivor: automate sending ppl to spec. Make the delay to return t…")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-09-14")
	table.insert(changelogs_change,"discord-log-shout: log shout messages to discord")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-08-13")
	table.insert(changelogs_change,"Add comment to clear_copy_history")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-08-13")
	table.insert(changelogs_change,"Fix evo reset when admins change difficulty")
	table.insert(changelogs_change,"AwesomePatrol")
	table.insert(changelogs_change,"2021-07-24")
	table.insert(changelogs_change,"clear-bp-history: overwrite copy history with miner")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-07-18")
	table.insert(changelogs_change,"inverse-game: disable friendly_fire")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-07-17")
	table.insert(changelogs_change,"inverse-game")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-06-27")
	table.insert(changelogs_change,"Pixie dust")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-06-20")
	table.insert(changelogs_change,"Remove all turrets from target pool")
	table.insert(changelogs_change,"cogito123")
	table.insert(changelogs_change,"2021-06-16")
	table.insert(changelogs_change,"Fix truncated ores around spawn area")
	table.insert(changelogs_change,"cogito123")
	table.insert(changelogs_change,"2021-06-08")
	table.insert(changelogs_change,"Add support for configurable spawn area ore patches")
	table.insert(changelogs_change,"cogito123")
	table.insert(changelogs_change,"2021-06-05")
	table.insert(changelogs_change,"Rework unit reanimation system")
	table.insert(changelogs_change,"cogito123")
	table.insert(changelogs_change,"2021-05-23")
	table.insert(changelogs_change,"Revert 'few commands for WE. no need revert after event end. (i think so :D )'")
	table.insert(changelogs_change,"1pulse")
	table.insert(changelogs_change,"2021-05-23")
	table.insert(changelogs_change,"few commands for WE. no need revert after event end. (i think so :D )")
	table.insert(changelogs_change,"ghost")
	table.insert(changelogs_change,"2021-05-23")
	table.insert(changelogs_change,"Biters bugfixes")
	table.insert(changelogs_change,"cogito123")
	table.insert(changelogs_change,"2021-05-22")
	table.insert(changelogs_change,"Remove additional teleport during game over phase")
	table.insert(changelogs_change,"cogito123")
	table.insert(changelogs_change,"2021-05-20")
	table.insert(changelogs_change,"Force chunk replication into lockstep")
	table.insert(changelogs_change,"cogito123")
	table.insert(changelogs_change,"2021-05-17")
	table.insert(changelogs_change,"Improvement to map generation performance")
	table.insert(changelogs_change,"cogito123")
	table.insert(changelogs_change,"2021-05-15")
	table.insert(changelogs_change,"Add two wood to inventory like in vanilla")
	table.insert(changelogs_change,"AwesomePatrol")
	table.insert(changelogs_change,"2021-05-15")
	table.insert(changelogs_change,"Always use a standard team name in post-game discord message (and more QoL stuff)")
	table.insert(changelogs_change,"AwesomePatrol")
	table.insert(changelogs_change,"2021-06-08")
	table.insert(changelogs_change,"2nd attempt at increasing difficulty")
	table.insert(changelogs_change,"AwesomePatrol")
	table.insert(changelogs_change,"2021-05-09")
	table.insert(changelogs_change,"More improvements 1")
	table.insert(changelogs_change,"1pulse")
	table.insert(changelogs_change,"2021-05-09")
	table.insert(changelogs_change,"Laser and mutagen suggestions")
	table.insert(changelogs_change,"1pulse")
	table.insert(changelogs_change,"2021-05-09")
	table.insert(changelogs_change,"Revert #140")
	table.insert(changelogs_change,"Hornwitser")
	table.insert(changelogs_change,"2021-05-01")
	table.insert(changelogs_change,"Update feeding.lua - buff endgame biters")
	table.insert(changelogs_change,"derkachdaniil")
	table.insert(changelogs_change,"2021-04-26")
	table.insert(changelogs_change,"Balance update 1")
	table.insert(changelogs_change,"1pulse")
	table.insert(changelogs_change,"2021-04-24")
	table.insert(changelogs_change,"Fix revive buff not applying")
	table.insert(changelogs_change,"AwesomePatrol")
	table.insert(changelogs_change,"2021-04-24")
	table.insert(changelogs_change,"fix revive biters")
	table.insert(changelogs_change,"ghost")
	table.insert(changelogs_change,"2021-03-23")
	table.insert(changelogs_change,"update-discord-link: update chatbot.lua with correct discord link,")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-03-23")
	table.insert(changelogs_change,"update-discord-link: free biter battles")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-03-18")
	table.insert(changelogs_change,"Revert 'Revert 'Disabled mines temporarily until better fix is found''")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2021-03-16")
	table.insert(changelogs_change,"Revert 'Disabled mines temporarily until better fix is found'")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2021-03-15")
	table.insert(changelogs_change,"Revert 'Difficulty voting by average'")
	table.insert(changelogs_change,"guppyfaced")
	table.insert(changelogs_change,"2021-03-15")
	table.insert(changelogs_change,"Fix ai pathfinding v2")
	table.insert(changelogs_change,"guppyfaced")
	table.insert(changelogs_change,"2021-03-15")
	table.insert(changelogs_change,"Limit mines")
	table.insert(changelogs_change,"derkachdaniil")
	table.insert(changelogs_change,"2021-03-15")
	table.insert(changelogs_change,"flamer upgrades buff")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-03-15")
	table.insert(changelogs_change,"Difficulty voting by average")
	table.insert(changelogs_change,"guymaor86")
	table.insert(changelogs_change,"2021-03-14")
	table.insert(changelogs_change,"fix difficulty reversion glitch for 480 min games")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-03-12")
	table.insert(changelogs_change,"stone copper buff")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-03-07")
	table.insert(changelogs_change,"Laser Buff")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-03-06")
	table.insert(changelogs_change,"Reduced Voting Options")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-03-06")
	table.insert(changelogs_change,"Update Peace Periods (slower increase)")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-03-06")
	table.insert(changelogs_change,"Add Peace Periods")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-03-06")
	table.insert(changelogs_change,"Reduced Difficulty for Choices below Normal")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-03-06")
	table.insert(changelogs_change,"Update difficulty_vote.lua ????")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-03-06")
	table.insert(changelogs_change,"Disabled Science Feeding before Voting Ends")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-03-06")
	table.insert(changelogs_change,"Update ai.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-02-26")
	table.insert(changelogs_change,"Revert 'Improve biter pathfinding'")
	table.insert(changelogs_change,"guymaor86")
	table.insert(changelogs_change,"2021-03-06")
	table.insert(changelogs_change,"Disabled mines temporarily until better fix is found")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2021-02-17")
	table.insert(changelogs_change,"torunament-feb21: removing free silo")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-02-26")
	table.insert(changelogs_change,"Fixed a bug that displays the seconds as a decimal")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2021-02-25")
	table.insert(changelogs_change,"Improve biter pathfinding")
	table.insert(changelogs_change,"AwesomePatrol")
	table.insert(changelogs_change,"2021-03-07")
	table.insert(changelogs_change,"damage updates customizable")
	table.insert(changelogs_change,"derkachdaniil")
	table.insert(changelogs_change,"2021-01-25")
	table.insert(changelogs_change,"Update init.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-25")
	table.insert(changelogs_change,"Removed update_difficulty() in ai.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-25")
	table.insert(changelogs_change,"Revert Blocking Science Sent before Voting Ends")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-25")
	table.insert(changelogs_change,"Update init.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-25")
	table.insert(changelogs_change,"Update ai.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-25")
	table.insert(changelogs_change,"Update main.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-25")
	table.insert(changelogs_change,"Update tables.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-25")
	table.insert(changelogs_change,"Updated endgame message upon Raven's request")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2021-03-01")
	table.insert(changelogs_change,"Updated Readme to include TOC and new URL to git repo")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2021-01-23")
	table.insert(changelogs_change,"Fix mines")
	table.insert(changelogs_change,"derkachdaniil")
	table.insert(changelogs_change,"2021-03-07")
	table.insert(changelogs_change,"changeable projectile_damage_upgrade")
	table.insert(changelogs_change,"derkachdaniil")
	table.insert(changelogs_change,"2021-01-18")
	table.insert(changelogs_change,"Update PR template")
	table.insert(changelogs_change,"guymaor86")
	table.insert(changelogs_change,"2021-01-17")
	table.insert(changelogs_change,"Fixup silo research changes")
	table.insert(changelogs_change,"AwesomePatrol")
	table.insert(changelogs_change,"2021-01-26")
	table.insert(changelogs_change,"Fix lag in long games")
	table.insert(changelogs_change,"AwesomePatrol")
	table.insert(changelogs_change,"2021-01-16")
	table.insert(changelogs_change,"Revert 'Update tables.lua'")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-16")
	table.insert(changelogs_change,"Revert 'Update tables.lua'")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-16")
	table.insert(changelogs_change,"Revert 'Update tables.lua'")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-16")
	table.insert(changelogs_change,"Revert 'Update tables.lua'")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-15")
	table.insert(changelogs_change,"Update tables.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-15")
	table.insert(changelogs_change,"Update tables.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-15")
	table.insert(changelogs_change,"Refactor free silo")
	table.insert(changelogs_change,"AwesomePatrol")
	table.insert(changelogs_change,"2021-01-15")
	table.insert(changelogs_change,"Added 2 turrets around silo")
	table.insert(changelogs_change,"guymaor86")
	table.insert(changelogs_change,"2021-01-15")
	table.insert(changelogs_change,"Added 10 burner miner drills when player spawns")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2021-01-13")
	table.insert(changelogs_change,"Update tables.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-15")
	table.insert(changelogs_change,"vote fix. now will round to higher difficulty.")
	table.insert(changelogs_change,"ghost")
	table.insert(changelogs_change,"2021-01-12")
	table.insert(changelogs_change,"Update tables.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2021-01-16")
	table.insert(changelogs_change,"Chat cmd updates")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2021-01-15")
	table.insert(changelogs_change,"tournament mode - admin can send message as a spectator")
	table.insert(changelogs_change,"guymaor86")
	table.insert(changelogs_change,"2021-01-15")
	table.insert(changelogs_change,"Additional commands")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-01-13")
	table.insert(changelogs_change,"difficulty-votes: clear vote table on revote")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-01-11")
	table.insert(changelogs_change,"Notifies both teams when a new level of biter spawns")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2021-03-12")
	table.insert(changelogs_change,"DashCee: Reducing DashCee's PR. Removing unused maps")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2021-01-11")
	table.insert(changelogs_change,"Added options to send more fish at a time, updated tooltip")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2020-12-27")
	table.insert(changelogs_change,"Prevent bots from tiling")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-29")
	table.insert(changelogs_change,"Updated discord link to never expire and put at top of info")
	table.insert(changelogs_change,"thePiedPiper13")
	table.insert(changelogs_change,"2020-12-27")
	table.insert(changelogs_change,"Fixed typos & unused variables")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2020-12-27")
	table.insert(changelogs_change,"Centralize ammo modifier values")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-27")
	table.insert(changelogs_change,"Updated Readme File with formatting, added Testing Instructions & modified text on PR's")
	table.insert(changelogs_change,"kajendra")
	table.insert(changelogs_change,"2020-12-27")
	table.insert(changelogs_change,"Pull request template")
	table.insert(changelogs_change,"guymaor86")
	table.insert(changelogs_change,"2020-12-27")
	table.insert(changelogs_change,"Update init.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-12-22")
	table.insert(changelogs_change,"Update init.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-12-22")
	table.insert(changelogs_change,"Update difficulty_vote.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-12-22")
	table.insert(changelogs_change,"Update tables.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-12-22")
	table.insert(changelogs_change,"Difficulty vote commands")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-22")
	table.insert(changelogs_change,"Update difficulty_vote.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-12-21")
	table.insert(changelogs_change,"issue-36: chatbot - on_console_chat - remove get server time as it causes problems")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-20")
	table.insert(changelogs_change,"Update ai.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-12-20")
	table.insert(changelogs_change,"put back normal values for nades")
	table.insert(changelogs_change,"1pulse")
	table.insert(changelogs_change,"2020-12-20")
	table.insert(changelogs_change,"Make river wider against rocket launchers")
	table.insert(changelogs_change,"guymaor86")
	table.insert(changelogs_change,"2020-12-20")
	table.insert(changelogs_change,"bb: adding evo threat and player list to end of game messages")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-18")
	table.insert(changelogs_change,"Update tables.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-12-17")
	table.insert(changelogs_change,"biter battle: send chat to discord even during tournament")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-17")
	table.insert(changelogs_change,"mirror map-not mirror reverse")
	table.insert(changelogs_change,"guymaor86")
	table.insert(changelogs_change,"2020-12-17")
	table.insert(changelogs_change,"New guide in readme")
	table.insert(changelogs_change,"guymaor86")
	table.insert(changelogs_change,"2020-12-17")
	table.insert(changelogs_change,"biter-battles: mvp stats only get sent once")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-15")
	table.insert(changelogs_change,"add mysticamber link for discord bot")
	table.insert(changelogs_change,"1pulse")
	table.insert(changelogs_change,"2020-12-14")
	table.insert(changelogs_change,"Update init.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-12-14")
	table.insert(changelogs_change,"File text updates")
	table.insert(changelogs_change,"DashCee")
	table.insert(changelogs_change,"2020-12-11")
	table.insert(changelogs_change,"biter-battles: adding north-chat and south-chat commands")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-11")
	table.insert(changelogs_change,"Contributing to repo")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-11")
	table.insert(changelogs_change,"Updated Biter battles map info (?) description to include 2 guides an…")
	table.insert(changelogs_change,"thePiedPiper13")
	table.insert(changelogs_change,"2020-12-10")
	table.insert(changelogs_change,"Updating readme")
	table.insert(changelogs_change,"DashCee")
	table.insert(changelogs_change,"2020-12-10")
	table.insert(changelogs_change,"default bbv2")
	table.insert(changelogs_change,"1pulse")
	table.insert(changelogs_change,"2020-12-10")
	table.insert(changelogs_change,"Update control.lua")
	table.insert(changelogs_change,"1pulse")
	table.insert(changelogs_change,"2020-12-10")
	table.insert(changelogs_change,"change vote system from average to median")
	table.insert(changelogs_change,"ghost")
	table.insert(changelogs_change,"2020-12-10")
	table.insert(changelogs_change,"Compress difficulty values upwards")
	table.insert(changelogs_change,"DashCee")
	table.insert(changelogs_change,"2020-12-10")
	table.insert(changelogs_change,"Updating the oil yield value from 0.27 to 0.5. ")
	table.insert(changelogs_change,"DashCee")
	table.insert(changelogs_change,"2020-12-10")
	table.insert(changelogs_change,"Update init.lua")
	table.insert(changelogs_change,"thePiedPiper13")
	table.insert(changelogs_change,"2020-12-10")
	table.insert(changelogs_change,"biter-battles: adding option to only send msg to a specific team as a spectator")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-10")
	table.insert(changelogs_change,"Chat")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-10")
	table.insert(changelogs_change,"mixed ore patches: adding multiplier")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-12-07")
	table.insert(changelogs_change,"biter-battles: difficulty vote - removing hard coded 7 in difficulties")
	table.insert(changelogs_change,"mysticamber")
	table.insert(changelogs_change,"2020-11-28")
	table.insert(changelogs_change,"Update init.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-11-28")
	table.insert(changelogs_change,"Update terrain.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-11-28")
	table.insert(changelogs_change,"Update difficulty_vote.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-11-27")
	table.insert(changelogs_change,"Update tables.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-11-27")
	table.insert(changelogs_change,"Update functions.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-11-28")
	table.insert(changelogs_change,"Update init.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-11-28")
	table.insert(changelogs_change,"Update main.lua")
	table.insert(changelogs_change,"St4telyRaven")
	table.insert(changelogs_change,"2020-11-27")
	table.insert(changelogs_change,"Update ai.lua")
	table.insert(changelogs_change,"St4telyRaven")
	
	local t = changelogs_scrollpanel.add { type = "table", name = "changelogs_header_table", column_count = 3 }
	local column_widths = {tonumber(115), tonumber(435), tonumber(230)}
	local headers = {
		[1] = "Date",
		[2] = "Change",
		[3] = "Author",
	}
	for _, w in ipairs(column_widths) do
	local label = t.add { type = "label", caption = headers[_] }
	label.style.minimal_width = w
	label.style.maximal_width = w
	label.style.font = "default-bold"
	label.style.font_color = { r=0.98, g=0.66, b=0.22 }
	end
	changelogs_panel_table = changelogs_scrollpanel.add { type = "table", column_count = 3 }
	if changelogs_change then
		for i = 1, #changelogs_change, 3 do
			local label = changelogs_panel_table.add { type = "label", name = "changelogs_date" .. i, caption = changelogs_change[i] }
			label.style.minimal_width = column_widths[1]
			label.style.maximal_width = column_widths[1]
			local label = changelogs_panel_table.add { type = "label", name = "changelogs_change" .. i, caption = changelogs_change[i+1] }
			label.style.minimal_width = column_widths[2]
			label.style.maximal_width = column_widths[2]
			local label = changelogs_panel_table.add { type = "label", name = "changelogs_author" .. i, caption = changelogs_change[i+2] }
			label.style.minimal_width = column_widths[3]
			label.style.maximal_width = column_widths[3]
		end
	end
end

function comfy_panel_get_active_frame(player)
	if not player.gui.left.comfy_panel then return false end
	if not player.gui.left.comfy_panel.tabbed_pane.selected_tab_index then return player.gui.left.comfy_panel.tabbed_pane.tabs[1].content end
	return player.gui.left.comfy_panel.tabbed_pane.tabs[player.gui.left.comfy_panel.tabbed_pane.selected_tab_index].content 
end

local build_config_gui = (function (player, frame)		
	local frame_changelogs = comfy_panel_get_active_frame(player)
	if not frame_changelogs then
		return
	end
	frame_changelogs.clear()
	add_changelogs(player, frame_changelogs)
end)

comfy_panel_tabs["Changelogs"] = {gui = build_config_gui, admin = false}