return {
    {
        number = 728,
        date = '2025-07-12',
        author = 'developer',
        comment = [[(#728) Mutagen strength changed:
  - [item=chemical-science-pack] 265 -> 292
  - [item=utility-science-pack] 2100 -> 2205
  Revert difficulty increase delayed by 30 minutes]],
    },
    {
        number = 727,
        date = '2025-07-12',
        author = 'TheBigZet',
        comment = [[(#727) Fixed incorret usages of table.concat]],
    },
    {
        number = 725,
        date = '2025-07-12',
        author = 'ness056',
        comment = [[(#725) Add \n and appending support to announces]],
    },
    {
        number = 722,
        date = '2025-05-31',
        author = 'gabrielchl',
        comment = [[(#722) Poll UI improvements and fix timer bug]],
    },
    {
        number = 719,
        date = '2025-05-31',
        author = 'TheBigZet',
        comment = [[(#719) Increase malloc function performance]],
    },
    {
        number = 721,
        date = '2025-05-24',
        author = 'L4m3ness',
        comment = [[(#721) Default difficulty changed:
  - ITYTD 25% -> 20%
  - HaND 38% -> 35%
  Mutagen strength changed:
  - [item=chemical-science-pack] 260 -> 265
  - [item=production-science-pack] 1029 -> 1050
  - [item=utility-science-pack] 1713 -> 2100
  - [item=space-science-pack] 3500 -> 4375
  Difficulty increase delayed by 30 minutes]],
    },
    {
        number = 714,
        date = '2025-03-30',
        author = 'TheBigZet',
        comment = [[(#714) Optimized destination position calculation for mirroring]],
    },
    {
        number = 713,
        date = '2025-03-30',
        author = 'morganc',
        comment = [[(#713) Enable ctrl-c for spectators]],
    },
    {
        number = 702,
        date = '2025-03-30',
        author = 'cogito123',
        comment = [[(#702) Fix spectate in some cases]],
    },
    {
        number = 708,
        date = '2025-03-30',
        author = 'TheBigZet',
        comment = [[(#708) Clear corpses tweaks]],
    },
    {
        number = 707,
        date = '2025-03-14',
        author = 'Max1000',
        comment = [[(#707) Fix an issue where an item held by the player was lost if they disconnected]],
    },
    {
        number = 710,
        date = '2025-03-14',
        author = 'cogito123',
        comment = [[(#710) Balance mutagen values:
  - Increase mutagen value of [item=chemical-science-pack] by 4%
  - Increase mutagen value of [item=utility-science-pack] by 2%
  - Decrease mutagen value of [item=production-science-pack] by 2%]],
    },
    {
        number = 703,
        date = '2025-03-14',
        author = 'TheBigZet',
        comment = [[(#703) Fix a desync issue when running the profiler in multiplayer]],
    },
    {
        number = 706,
        date = '2025-03-14',
        author = 'TheBigZet',
        comment = [[(#706) Prevent messages from being printed to disconnected players when using /nth, /sth, or /spectator-chat]],
    },
    {
        number = 705,
        date = '2025-03-14',
        author = 'TheBigZet',
        comment = [[(#705) Follow-up optimization for #692]],
    },
    {
        number = 709,
        date = '2025-03-14',
        author = 'morganc',
        comment = [[(#709) Remove some unused code]],
    },
    {
        number = 692,
        date = '2025-02-22',
        author = 'TheBigZet',
        comment = [[(#692) Improve biter spawning performance by optimizing the name selection logic]],
    },
    {
        number = 701,
        date = '2025-02-21',
        author = 'cogito123',
        comment = [[(#701) Add an admin-only /announce command]],
    },
    {
        number = 700,
        date = '2025-02-18',
        author = 'cogito123',
        comment = [[(#700) Fix an issue that prevented the tooltip from appearing when hovering over the evolution icon]],
    },
    {
        number = 698,
        date = '2025-02-14',
        author = 'TheBigZet',
        comment = [[(#698) Fix an issue where the [img=item/heavy-armor] map icon would not be removed after the corpse was picked up or expired]],
    },
    {
        number = 693,
        date = '2025-02-14',
        author = 'morganc',
        comment = [[(#693) Increase measurement granularity in the on_tick handler]],
    },
    {
        number = 691,
        date = '2025-02-13',
        author = 'TheBigZet',
        comment = [[(#691) Miscellaneous changes to type annotations and variable scoping]],
    },
    {
        number = 686,
        date = '2025-02-12',
        author = 'Data-',
        comment = [[(#686) [color=yellow]⚡[/color] Major refactoring and optimization of terrain generation. Older seeds may produce different terrain due to changes in RNG and increased determinism]],
    },
    {
        number = 696,
        date = '2025-02-07',
        author = 'RedRafe',
        comment = [[(#696) While in captain mode, hide both teams’ chat from spectators until the match starts]],
    },
    {
        number = 674,
        date = '2025-02-07',
        author = 'cogito123',
        comment = [[(#674) Fix an issue preventing a player from being correctly assigned as a spectator when kicked out of the team by the captain]],
    },
    {
        number = 690,
        date = '2025-01-30',
        author = 'RedRafe',
        comment = [[(#690) Fix a bug that allowed the 'send all' button to be used before the match started]],
    },
    {
        number = 685,
        date = '2025-01-30',
        author = 'TheBigZet',
        comment = [[(#685) Speed up UI building by referencing shared elements and data rather than duplicating them for every player]],
    },
    {
        number = 683,
        date = '2025-01-30',
        author = 'morganc',
        comment = [[(#683) Profile the execution time of event handlers and log measurements once per minute]],
    },
    {
        number = 680,
        date = '2025-01-30',
        author = 'cogito123',
        comment = [[(#680) Minor optimizations to the data collection used by the research UI]],
    },
    {
        number = 681,
        date = '2025-01-25',
        author = 'RedRafe',
        comment = [[(#681) Improve performance of event dispatcher by getting rid of memory allocations]],
    },
    {
        number = 679,
        date = '2025-01-24',
        author = 'morganc',
        comment = [[(#679) Remove unused alerts.lua file]],
    },
    {
        number = 676,
        date = '2025-01-24',
        author = 'morganc',
        comment = [[(#676) Remove unused duplicate biter_raffle.lua file]],
    },
    {
        number = 668,
        date = '2025-01-23',
        author = 'cogito123',
        comment = [[(#668) Rework how changelog tab gets information to avoid any data processing inside scenario code]],
    },
    {
        number = 675,
        date = '2025-01-20',
        author = 'morganc',
        comment = [[(#675) Profile GUI once per minute]],
    },
    {
        number = 673,
        date = '2025-01-19',
        author = 'cogito123',
        comment = [[(#673) Fix the regression introduced in #670 that would make players lose their character when rejoining]],
    },
    {
        number = 670,
        date = '2025-01-12',
        author = 'cogito123',
        comment = [[(#670) Fix the issue where new joiners would leave their character on default Nauvis surface which degraded performance]],
    },
    {
        number = 666,
        date = '2025-01-11',
        author = 'Data-',
        comment = [[(#666) Make captains join random forces]],
    },
    {
        number = 662,
        date = '2025-01-11',
        author = 'Data-',
        comment = [[(#662) Fix the southern silo position used for biter tracking, which was not symmetrical with the northern silo]],
    },
    {
        number = 667,
        date = '2025-01-09',
        author = 'cogito123',
        comment = [[(#667) Changes to terrain mirroring:
  - Optimize spawn area generation on top of a lake
  - Fix the south team having water under spawn due to broken mirroring of hidden tiles from the north]],
    },
    {
        number = 665,
        date = '2025-01-06',
        author = 'Data-',
        comment = [[(#665) Fix a bug in /calc-send that resulted in the wrong values when inputting parameters while carrying science packs in the inventory]],
    },
    {
        number = 664,
        date = '2025-01-06',
        author = 'cogito123, developer',
        comment = [[(#664) Fix a player losing their character when switching teams with the camera centered on a chunk that was not yet generated while in remote view]],
    },
    {
        number = 663,
        date = '2025-01-04',
        author = 'cogito123',
        comment = [[(#663) Fix a crash when calling /difficulty-close-vote]],
    },
    {
        number = 660,
        date = '2025-01-03',
        author = 'cogito123',
        comment = [[(#660) Second attempt to workaround double surface bug]],
    },
    {
        number = 658,
        date = '2025-01-02',
        author = 'cogito123',
        comment = [[(#658) Changes to difficulty:
  - Implement new "have a nice day" (HaND) difficulty
  - Change hard difficulty to 200%
  - Remove nightmare difficulty
  - Refresh difficulty colors for better representation
  - The difficulty voting menu now follows the theme selected in the config menu]],
    },
    {
        number = 661,
        date = '2025-01-01',
        author = 'cogito123',
        comment = [[(#661) Adapt for 2.0.26 deprecated 'minable' flag]],
    },
    {
        number = 655,
        date = '2024-12-29',
        author = 'Data-',
        comment = [[(#655) Changes related to /inventory-costs:
  - Fix accessing the inventory of disconnected or dead players
  - Count inventory costs for players who switched back to spectator]],
    },
    {
        number = 659,
        date = '2024-12-29',
        author = 'cogito123',
        comment = [[(#659) Fix a truncated player list due to missing icons]],
    },
    {
        number = 656,
        date = '2024-12-29',
        author = 'cogito123',
        comment = [[(#656) First attempt at fixing the double surface bug]],
    },
    {
        number = 657,
        date = '2024-12-28',
        author = 'Data-, floortiler',
        comment = [[(#657) Fix laser damage to match values from 1.1]],
    },
    {
        number = 653,
        date = '2024-12-17',
        author = 'developer',
        comment = [[(#653) Fix snow transition on edges of the new year tree]],
    },
    {
        number = 654,
        date = '2024-12-17',
        author = 'Data-',
        comment = [[(#654) Fix issues related to remote view (non-exhaustive list):
  - Admin teleporting of a driving player while they are in remote view fails
  - Admin teleporting of a dead player error (in log)
  - Admin "bring player/bring to spawn/go to player": incorrect destination position/surface while in remote view
  - Admin "spank/damage": incorrect particle position while the target is in remote view
  - Show player in player list: remote view position was used instead of physical
  - "/where" command view: remote view position was used instead of physical
  - Suspend player remote viewing gulag failure/double suspend
  - Suspend player in remote view leaves corpses in an invalid location
  - Player going into spectate mode drops burner miners on the remote-viewed position
  - Player receiving burners via burner balance spills overflow to the remote view position
  - Player joining a team while remote viewing another surface spawns on the incorrect surface
  - Player rejoining a team in an incorrect location after AFK forced them to spectate in remote view
  - Spying on the other team was done incorrectly by using the remote view positions of enemy players
  - Players could bypass the requirement to be near the spawn point and just go spectate via remote view
  - Players could refuse to be teleported to spec island by being in remote view and driving
  - Outposting players were auto-tagged based on their remote view positions
  - Freeing a player from gulag restored them to their remote view position
  - Player leaves dummy characters along with corpses when being suspended in remote view or in editor mode, among multiple other improperly handled corner cases
  - Stop jailed players from driving in remote view]],
    },
    {
        number = 651,
        date = '2024-12-04',
        author = 'Data-',
        comment = [[(#651) Fix minable wrecks yielding incorrect loot]],
    },
    {
        number = 650,
        date = '2024-12-03',
        author = 'Data-',
        comment = [[(#650) Batch of minor fixes:
  - Fix /jail and /free notifications
  - Fix the offset of drawn text/graphics]],
    },
    {
        number = 649,
        date = '2024-12-02',
        author = 'Data-',
        comment = [[(#649) Further adaptations to 2.0.22 breaking API changes]],
    },
    {
        number = 647,
        date = '2024-11-28',
        author = 'cogito123',
        comment = [[(#647) Fix the /follow command and other utilities that use zoom_to_world]],
    },
    {
        number = 648,
        date = '2024-11-28',
        author = 'Data-',
        comment = [[(#648) Batch of fixes:
  - Adapt for a backward-incompatible change in 2.0.22 that caused a crash when using /inventory
  - Fix /inventory-costs stack overflow
  - Fix a grayed-out GUI in the /inventory widget for armor slots]],
    },
    {
        number = 645,
        date = '2024-11-27',
        author = 'Data-',
        comment = [[(#645) Fix an issue with a grayed-out GUI in the /inventory widget]],
    },
    {
        number = 646,
        date = '2024-11-26',
        author = 'cogito123',
        comment = [[(#646) Fix a segfault when blueprinting an underground pipe across a river]],
    },
    {
        number = 644,
        date = '2024-11-23',
        author = 'cogito123',
        comment = [[(#644) Fix and remove restrictions on using the GUI from remote view]],
    },
    {
        number = 642,
        date = '2024-11-23',
        author = 'cogito123',
        comment = [[(#642) Fix broken alerts about entities getting attacked]],
    },
    {
        number = 641,
        date = '2024-11-18',
        author = 'cogito123',
        comment = [[(#641) Re-enable chat tech notifications, as it was suppressing messages generated even by your own force]],
    },
    {
        number = 640,
        date = '2024-11-15',
        author = 'cogito123',
        comment = [[(#640) Batch of fixes:
  - Don't unlock [technology=space-science-pack] when unlocking [technology=rocket-silo] because it's now done automatically on satellite launch
  - Fix some settings not showing up for admins
  - Fix new year tree generation
  - Remove code related to other comfy maps from the comfy panel]],
    },
    {
        number = 638,
        date = '2024-11-09',
        author = 'cogito123',
        comment = [[(#638) Remove the restriction on manually launching a rocket, as it's no longer possible to send anything other than a satellite (unlike in 1.1)]],
    },
    {
        number = 637,
        date = '2024-11-08',
        author = 'cogito123',
        comment = [[(#637) Batch of fixes for issues found in multiplayer testing:
  - Don't show spectators flying around the map
  - Fix the poll vote
  - Disable the broken /follow
  - Restrict GUI options while in remote view
  - Force a player out of remote view when suspending or switching teams
  - Fix looting wrecks
  - Change the sound when receiving pings]],
    },
    {
        number = 636,
        date = '2024-11-08',
        author = 'cogito123',
        comment = [[(#636) Fix a player losing their character when joining a team while in remote view]],
    },
    {
        number = 635,
        date = '2024-11-05',
        author = 'cogito123',
        comment = [[(#635) Workaround broken biter pathing with 1 tick wander commands]],
    },
    {
        number = 633,
        date = '2024-11-04',
        author = 'RedRafe',
        comment = [[(#633) Adjust nest kill score and threat value calculation by a factor of 1 + 9 * evo ^ 2.25. Since 2.0.x nest health is increased by the evolution factor, see: FFF-427]],
    },
    {
        number = 631,
        date = '2024-11-04',
        author = 'RedRafe',
        comment = [[(#631) Miscellaneous and AI fixes related to 2.0.x]],
    },
    {
        number = 630,
        date = '2024-11-04',
        author = 'cogito123',
        comment = [[(#630) Balance mutagen values:
  - Lower the mutagen value of [item=space-science-pack] by 30%
  - Increase the mutagen value of [item=utility-science-pack] by 5%]],
    },
    {
        number = 634,
        date = '2024-11-03',
        author = 'cogito123',
        comment = [[(#634) Temporarily disable /inventory-costs due to stack overflow]],
    },
    {
        number = 632,
        date = '2024-11-03',
        author = 'cogito123',
        comment = [[(#632) Replace all uses of [img=item/landfill] (landfill) with [img=tile/dirt-1] (dirt-1) in the scenario, as it can be picked up]],
    },
    {
        number = 629,
        date = '2024-10-25',
        author = 'cogito123',
        comment = [[(#629) Add 2.0.x support, 5th batch of commits]],
    },
    {
        number = 628,
        date = '2024-10-24',
        author = 'cogito123',
        comment = [[(#628) Add 2.0.x support, 4th batch of commits]],
    },
    {
        number = 627,
        date = '2024-10-23',
        author = 'cogito123',
        comment = [[(#627) Add 2.0.x support, 3rd batch of commits]],
    },
    {
        number = 626,
        date = '2024-10-22',
        author = 'cogito123',
        comment = [[(#626) Add 2.0.x support, 2nd batch of commits]],
    },
    {
        number = 625,
        date = '2024-10-21',
        author = 'cogito123',
        comment = [[(#625) Add 2.0.x support, 1st batch of commits]],
    },
    {
        number = 624,
        date = '2024-10-14',
        author = 'direwolfclaw',
        comment = [[(#624) Fix captain text render]],
    },
    {
        number = 623,
        date = '2024-10-13',
        author = 'developer',
        comment = [[(#623) Fix send science after game over]],
    },
    {
        number = 621,
        date = '2024-09-28',
        author = 'developer',
        comment = [[(#621) Fix send science when disabled]],
    },
    {
        number = 620,
        date = '2024-09-26',
        author = 'developer',
        comment = [[(#620) move biter area slope to config]],
    },
    {
        number = 617,
        date = '2024-09-14',
        author = 'Arktischer',
        comment = [[(#617) added a more specific warning for untrusted players]],
    },
    {
        number = 616,
        date = '2024-09-14',
        author = 'outstanding',
        comment = [[(#616) Create test-readme.md]],
    },
    {
        number = 614,
        date = '2024-09-09',
        author = 'outstanding',
        comment = [[(#614) Added instalation guide]],
    },
    {
        number = 612,
        date = '2024-09-05',
        author = 'Arktischer',
        comment = [[(#612) added threat farm special]],
    },
    {
        number = 611,
        date = '2024-09-02',
        author = 'cliff_build',
        comment = [[(#611) Add vice-captain support]],
    },
    {
        number = 610,
        date = '2024-08-29',
        author = 'cliff_build',
        comment = [[(#610) Add message to logging to differentiate community-picks from captain]],
    },
    {
        number = 608,
        date = '2024-08-29',
        author = 'cliff_build',
        comment = [[(#608) Community pick fixes/logging]],
    },
    {
        number = 607,
        date = '2024-08-29',
        author = 'cliff_build',
        comment = [[(#607) captain community pick: ignore where people place themselves in the list]],
    },
    {
        number = 606,
        date = '2024-08-29',
        author = 'cliff_build',
        comment = [[(#606) community pick: default to no captains, allow ref to decide]],
    },
    {
        number = 609,
        date = '2024-08-29',
        author = 'cliff_build',
        comment = [[(#609) Fix bug with send-science permission]],
    },
    {
        number = 605,
        date = '2024-08-22',
        author = 'Ragnarok77',
        comment = [[(#605) Add back missing text for automatic captain poll that got removed]],
    },
    {
        number = 604,
        date = '2024-08-21',
        author = 'cliff_build',
        comment = [[(#604) Community pick captain improvements]],
    },
    {
        number = 602,
        date = '2024-08-21',
        author = 'cliff_build',
        comment = [[(#602) afk_kick: only kick once game starts]],
    },
    {
        number = 597,
        date = '2024-08-20',
        author = 'Ragnarok77',
        comment = [[(#597) Automatic captain system without referee]],
    },
    {
        number = 601,
        date = '2024-08-19',
        author = 'cliff_build',
        comment = [[(#601) rename /spectator-follow to /follow for better tab-completion]],
    },
    {
        number = 600,
        date = '2024-08-18',
        author = 'cliff_build',
        comment = [[(#600) captains games: add 'community picked teams' mode]],
    },
    {
        number = 599,
        date = '2024-08-18',
        author = 'cliff_build',
        comment = [[(#599) teamstats: fix space-sci-equiv-produced number]],
    },
    {
        number = 598,
        date = '2024-08-18',
        author = 'cliff_build',
        comment = [[(#598) add /spectator-follow command]],
    },
    {
        number = 596,
        date = '2024-08-15',
        author = 'ness056',
        comment = [[(#596) Fix desync]],
    },
    {
        number = 595,
        date = '2024-08-15',
        author = 'cliff_build',
        comment = [[(#595) fix join-random]],
    },
    {
        number = 594,
        date = '2024-08-14',
        author = 'cliff_build',
        comment = [[(#594) Replace "reanim_chance" with "biter_health_factor"]],
    },
    {
        number = 593,
        date = '2024-08-13',
        author = 'cliff_build',
        comment = [[(#593) Teamstats improvements]],
    },
    {
        number = 588,
        date = '2024-08-13',
        author = 'ness056',
        comment = [[(#588) Add event priority]],
    },
    {
        number = 590,
        date = '2024-08-11',
        author = 'cliff_build',
        comment = [[(#590) Fix /replaceCaptainNorth command]],
    },
    {
        number = 589,
        date = '2024-08-10',
        author = 'developer',
        comment = [[(#589) Fix reply notification to wrong player]],
    },
    {
        number = 586,
        date = '2024-08-07',
        author = 'Max1000',
        comment = [[(#586) You can turn off flashlight in config]],
    },
    {
        number = 585,
        date = '2024-08-07',
        author = 'RedRafe',
        comment = [[(#585) Feedbacks & fixes]],
    },
    {
        number = 584,
        date = '2024-08-06',
        author = 'Max1000',
        comment = [[(#584) add message for discord server chat when match starts]],
    },
    {
        number = 583,
        date = '2024-08-06',
        author = 'RedRafe',
        comment = [[(#583) UI updates]],
    },
    {
        number = 582,
        date = '2024-08-06',
        author = 'cliff_build',
        comment = [[(#582) teamstats: log json version of stats in various places]],
    },
    {
        number = 578,
        date = '2024-08-06',
        author = 'Max1000',
        comment = [[(#578) now can't join team if reroll didn't end.]],
    },
    {
        number = 579,
        date = '2024-08-06',
        author = 'Max1000',
        comment = [[(#579) Synchronize voting time with displayed time in gui.]],
    },
    {
        number = 581,
        date = '2024-08-06',
        author = 'RedRafe',
        comment = [[(#581) UI merge]],
    },
    {
        number = 580,
        date = '2024-07-27',
        author = 'cliff_build',
        comment = [[(#580) Increase reroll time to 45 seconds]],
    },
    {
        number = 576,
        date = '2024-07-27',
        author = 'cliff_build',
        comment = [[(#576) teamstats: add a bit more info]],
    },
    {
        number = 577,
        date = '2024-07-27',
        author = 'Ragnarok77',
        comment = [[(#577) Reduce the majority required for a map reroll from 75% to 66%]],
    },
    {
        number = 575,
        date = '2024-07-20',
        author = 'gabrielchl',
        comment = [[(#575) fix: teams player list no longer sorted]],
    },
    {
        number = 571,
        date = '2024-07-20',
        author = 'RedRafe',
        comment = [[(#571) Charting fixes]],
    },
    {
        number = 573,
        date = '2024-07-19',
        author = 'Max1000',
        comment = [[(#573) Fix, prevent voting same difficulty: Now also in captains.]],
    },
    {
        number = 574,
        date = '2024-07-19',
        author = 'Ragnarok77',
        comment = [[(#574) Bugfix captain : dont show task group for spectators]],
    },
    {
        number = 572,
        date = '2024-07-19',
        author = 'gabrielchl',
        comment = [[(#572) feat(captains): revert captains join info panel player list sort logic]],
    },
    {
        number = 568,
        date = '2024-07-17',
        author = 'RedRafe',
        comment = [[(#568) Fix ping alert and map countdown sound bugs]],
    },
    {
        number = 561,
        date = '2024-07-17',
        author = 'Ragnarok77',
        comment = [[(#561) Implement task system for captain game]],
    },
    {
        number = 564,
        date = '2024-07-15',
        author = 'RedRafe',
        comment = [[(#564) Add inventory tracking for lost item teamstats]],
    },
    {
        number = 560,
        date = '2024-07-14',
        author = 'ness056',
        comment = [[(#560) Special game desync fixes and change in removable functions]],
    },
    {
        number = 567,
        date = '2024-07-14',
        author = 'cliff_build',
        comment = [[(#567) /close-difficulty-vote: add logging if difficulty changes]],
    },
    {
        number = 566,
        date = '2024-07-14',
        author = 'Ragnarok77',
        comment = [[(#566) Captain : Fix wrong logging of game length in DB]],
    },
    {
        number = 556,
        date = '2024-07-13',
        author = 'Max1000',
        comment = [[(#556) burners-balance. now player drop burners when left game]],
    },
    {
        number = 565,
        date = '2024-07-13',
        author = 'cliff_build',
        comment = [[(#565) captains on_player_left_game: fix bugs hopefully]],
    },
    {
        number = 563,
        date = '2024-07-13',
        author = 'RedRafe',
        comment = [[(#563) Sound enhancement]],
    },
    {
        number = 562,
        date = '2024-07-13',
        author = 'cliff_build',
        comment = [[(#562) /close-difficulty-vote: add optional param to force difficulty]],
    },
    {
        number = 559,
        date = '2024-07-13',
        author = 'cliff_build',
        comment = [[(#559) End game stats UI]],
    },
    {
        number = 558,
        date = '2024-07-10',
        author = 'gabrielchl',
        comment = [[(#558) feat(captains): remove player from joiner list on disconnect]],
    },
    {
        number = 557,
        date = '2024-07-10',
        author = 'gabrielchl',
        comment = [[(#557) feat(captains): order and colorize player names in info panels]],
    },
    {
        number = 555,
        date = '2024-07-08',
        author = 'Ragnarok77',
        comment = [[(#555) Captain : Difficulty is now chosen before captain start picking players]],
    },
    {
        number = 552,
        date = '2024-07-08',
        author = 'Max1000',
        comment = [[(#552) Special games, add ore pattern  in mixed ore]],
    },
    {
        number = 554,
        date = '2024-07-08',
        author = 'gabrielchl',
        comment = [[(#554) feat(ui/captains): minor join info panel layout update]],
    },
    {
        number = 553,
        date = '2024-07-08',
        author = 'cliff_build',
        comment = [[(#553) captains: fix some weird conditions with "I do not want to play/captain"]],
    },
    {
        number = 551,
        date = '2024-07-03',
        author = 'cliff_build',
        comment = [[(#551) captains: allow players to un-volunteer to play/captain]],
    },
    {
        number = 550,
        date = '2024-07-03',
        author = 'cliff_build',
        comment = [[(#550) add /inventory-costs comand]],
    },
    {
        number = 548,
        date = '2024-07-03',
        author = 'cliff_build',
        comment = [[(#548) captains: fix picking of offline players]],
    },
    {
        number = 549,
        date = '2024-07-03',
        author = 'cliff_build',
        comment = [[(#549) Captain pick order rework]],
    },
    {
        number = 546,
        date = '2024-07-03',
        author = 'Max1000',
        comment = [[(#546) implement burners balance.]],
    },
    {
        number = 547,
        date = '2024-07-02',
        author = 'cliff_build',
        comment = [[(#547) /difficulty-revote no longer resets evo after teams have fed]],
    },
    {
        number = 545,
        date = '2024-07-01',
        author = 'cliff_build',
        comment = [[(#545) Fix captains pick-UI when groups are disabled]],
    },
    {
        number = 544,
        date = '2024-06-23',
        author = 'Ragnarok77',
        comment = [[(#544) Captain event : show amount of players before the players list]],
    },
    {
        number = 543,
        date = '2024-06-21',
        author = 'cliff_build',
        comment = [[(#543) Main gui: make buttons much more responsive]],
    },
    {
        number = 542,
        date = '2024-06-20',
        author = 'Ragnarok77',
        comment = [[(#542) Implement min playtime of 30 min to join captain game]],
    },
    {
        number = 541,
        date = '2024-06-18',
        author = 'cliff_build',
        comment = [[(#541) Always show evo/threat]],
    },
    {
        number = 540,
        date = '2024-06-18',
        author = 'cliff_build',
        comment = [[(#540) biter target behavior: attack silo on pathfinding error]],
    },
    {
        number = 539,
        date = '2024-06-14',
        author = 'cliff_build',
        comment = [[(#539) Random UI changes]],
    },
    {
        number = 538,
        date = '2024-06-14',
        author = 'developer',
        comment = [[(#538) Fix reply ping]],
    },
    {
        number = 536,
        date = '2024-06-09',
        author = 'penguinencounter',
        comment = [[(#536) Poll UI styles]],
    },
    {
        number = 537,
        date = '2024-06-07',
        author = 'developer',
        comment = [[(#537) Add `on_player_joined_team` event]],
    },
    {
        number = 535,
        date = '2024-06-06',
        author = 'ness056',
        comment = [[(#535) UI improvement]],
    },
    {
        number = 532,
        date = '2024-05-30',
        author = 'cliff_build',
        comment = [[(#532) ping messages: fix permanent-ping from message before map reset]],
    },
    {
        number = 534,
        date = '2024-05-30',
        author = 'cliff_build',
        comment = [[(#534) More errors from logs fixes]],
    },
    {
        number = 533,
        date = '2024-05-29',
        author = 'cliff_build',
        comment = [[(#533) use game.get_player in more places]],
    },
    {
        number = 531,
        date = '2024-05-27',
        author = 'developer',
        comment = [[(#531) Add a new Patches type for mixed ore map special]],
    },
    {
        number = 528,
        date = '2024-05-26',
        author = 'cliff_build',
        comment = [[(#528) Clean up errors in log]],
    },
    {
        number = 530,
        date = '2024-05-26',
        author = 'cliff_build',
        comment = [[(#530) Poll duration: make it easier to make short-duration polls]],
    },
    {
        number = 529,
        date = '2024-05-26',
        author = 'cliff_build',
        comment = [[(#529) Fix too-many-captains race condition]],
    },
    {
        number = 527,
        date = '2024-05-25',
        author = 'cliff_build',
        comment = [[(#527) Partially revert pathfinder settings change (#502)]],
    },
    {
        number = 524,
        date = '2024-05-24',
        author = 'cliff_build',
        comment = [[(#524) Captains games: add randomized-fair picking mode]],
    },
    {
        number = 523,
        date = '2024-05-24',
        author = 'cliff_build',
        comment = [[(#523) Ping improvements, and default to on]],
    },
    {
        number = 525,
        date = '2024-05-24',
        author = 'developer',
        comment = [[(#525) Fix error on non exist inventory]],
    },
    {
        number = 526,
        date = '2024-05-24',
        author = 'cliff_build',
        comment = [[(#526) Add global.threat_multiplier]],
    },
    {
        number = 522,
        date = '2024-05-21',
        author = 'sciqu',
        comment = [[(#522) new command /current-map-seed]],
    },
    {
        number = 521,
        date = '2024-05-21',
        author = 'cliff_build',
        comment = [[(#521) utils/queue: fix off by one error]],
    },
    {
        number = 520,
        date = '2024-05-21',
        author = 'cliff_build',
        comment = [[(#520) tiny captains game cleanups]],
    },
    {
        number = 518,
        date = '2024-05-21',
        author = 'cliff_build',
        comment = [[(#518) Initial/experimental support for @ping in chat]],
    },
    {
        number = 513,
        date = '2024-05-20',
        author = 'penguinencounter',
        comment = [[(#513) flib + Research overview screen rework (again)]],
    },
    {
        number = 519,
        date = '2024-05-20',
        author = 'cliff_build',
        comment = [[(#519) Captains more improvements]],
    },
    {
        number = 517,
        date = '2024-05-18',
        author = 'cliff_build',
        comment = [[(#517) captains game kick from team: use a dropdown rather than a textbox]],
    },
    {
        number = 516,
        date = '2024-05-17',
        author = 'penguinencounter',
        comment = [[(#516) Use Factorio button styles instead of font color on Captain UI elements for enhanced readability]],
    },
    {
        number = 515,
        date = '2024-05-16',
        author = 'cliff_build',
        comment = [[(#515) sciencelogs: fix a bug when looking at the UI before any sends]],
    },
    {
        number = 511,
        date = '2024-05-16',
        author = 'cliff_build',
        comment = [[(#511) Captains games join UI rework]],
    },
    {
        number = 512,
        date = '2024-05-15',
        author = 'cliff_build',
        comment = [[(#512) support "/instant_map_reset current" to reset to current seed]],
    },
    {
        number = 510,
        date = '2024-05-15',
        author = 'cliff_build',
        comment = [[(#510) Stop always broadcasting admin chat messages]],
    },
    {
        number = 507,
        date = '2024-05-09',
        author = 'Ragnarok77',
        comment = [[(#507) Auto trust after 24h and code cleaning]],
    },
    {
        number = 508,
        date = '2024-05-09',
        author = 'Ragnarok77',
        comment = [[(#508) Captain : remove ground markers of new/not new/vet/speedrunner and spect part]],
    },
    {
        number = 509,
        date = '2024-05-09',
        author = 'developer',
        comment = [[(#509) Fix mining history is empty]],
    },
    {
        number = 505,
        date = '2024-05-08',
        author = 'Ragnarok77',
        comment = [[(#505) Captain : Add total playtime in picking up and ordered by playtime]],
    },
    {
        number = 500,
        date = '2024-05-04',
        author = 'cliff_build',
        comment = [[(#500) Admin option: MoveToSpawn]],
    },
    {
        number = 503,
        date = '2024-05-04',
        author = 'cliff_build',
        comment = [[(#503) group names: do not allow "()[]=" characters]],
    },
    {
        number = 504,
        date = '2024-05-04',
        author = 'cliff_build',
        comment = [[(#504) Remove "tech-spy" function from captains games]],
    },
    {
        number = 499,
        date = '2024-05-04',
        author = 'cliff_build',
        comment = [[(#499) Research UI improvements]],
    },
    {
        number = 502,
        date = '2024-05-03',
        author = 'ness056',
        comment = [[(#502) Changes to the pathfinder settings]],
    },
    {
        number = 501,
        date = '2024-05-03',
        author = 'cliff_build',
        comment = [[(#501) Remove rule about overlapping flamethrower turrets]],
    },
    {
        number = 498,
        date = '2024-05-01',
        author = 'penguinencounter',
        comment = [[(#498) Research summary: use progress bar for incomplete tech]],
    },
    {
        number = 497,
        date = '2024-05-01',
        author = 'thePiedPiper13',
        comment = [[(#497) Update infinity_chest.lua]],
    },
    {
        number = 495,
        date = '2024-04-27',
        author = 'cliff_build',
        comment = [[(#495) Implement flamethrower turret overlap protection in code]],
    },
    {
        number = 490,
        date = '2024-04-25',
        author = 'cliff_build',
        comment = [[(#490) Add a new research info window (disabled by default)]],
    },
    {
        number = 494,
        date = '2024-04-25',
        author = 'cliff_build',
        comment = [[(#494) Always use the new threat logic]],
    },
    {
        number = 491,
        date = '2024-04-23',
        author = 'vadcx',
        comment = [[(#491) Reduce size of Captain Countdown again (-200 KiB)]],
    },
    {
        number = 464,
        date = '2024-04-21',
        author = 'gsquaredxc',
        comment = [[(#464) Remove Game.get_player_by_index and Game.get_player_from_any]],
    },
    {
        number = 480,
        date = '2024-04-21',
        author = 'cliff_build',
        comment = [[(#480) Speed up ai_targets random target selection]],
    },
    {
        number = 489,
        date = '2024-04-21',
        author = 'vadcx',
        comment = [[(#489) Change color, fix and refactor Captain mode text]],
    },
    {
        number = 488,
        date = '2024-04-21',
        author = 'vadcx',
        comment = [[(#488) Compress Captain Countdown images (3.1MB -> 860KB, 0.27x size)]],
    },
    {
        number = 486,
        date = '2024-04-20',
        author = 'vadcx',
        comment = [[(#486) Comment hardcoded values for _LIFECYCLE checks]],
    },
    {
        number = 481,
        date = '2024-04-20',
        author = 'cliff_build',
        comment = [[(#481) Fix error printing to show real stacktraces]],
    },
    {
        number = 484,
        date = '2024-04-18',
        author = 'vadcx',
        comment = [[(#484) profiler.lua: gracefully disable profiler in unsupported versions]],
    },
    {
        number = 474,
        date = '2024-04-16',
        author = 'DrButtons',
        comment = [[(#474) Limit suspend voting to suspendee's force]],
    },
    {
        number = 472,
        date = '2024-04-16',
        author = 'cliff_build',
        comment = [[(#472) New/faster/more-predictable revive mechanics]],
    },
    {
        number = 471,
        date = '2024-04-12',
        author = 'cliff_build',
        comment = [[(#471) Add code support for feeding without specifying player]],
    },
    {
        number = 469,
        date = '2024-04-09',
        author = 'DrButtons',
        comment = [[(#469) Add script and framework for benchmarking]],
    },
    {
        number = 466,
        date = '2024-04-07',
        author = 'cliff_build',
        comment = [[(#466) Add experimental new threat logic]],
    },
    {
        number = 468,
        date = '2024-04-07',
        author = 'cliff_build',
        comment = [[(#468) Fix on_built_entity]],
    },
    {
        number = 465,
        date = '2024-04-04',
        author = 'gsquaredxc',
        comment = [[(#465) Remove unused file map_score.lua]],
    },
    {
        number = 463,
        date = '2024-04-04',
        author = 'LackOfTropicalFruit',
        comment = [[(#463) Update killscore to be proportionate to threat]],
    },
    {
        number = 457,
        date = '2024-04-04',
        author = 'DrButtons',
        comment = [[(#457) Delete player_modifiers.lua]],
    },
    {
        number = 455,
        date = '2024-04-04',
        author = 'DrButtons',
        comment = [[(#455) Delete Unused files in functions folder]],
    },
    {
        number = 462,
        date = '2024-03-27',
        author = 'LackOfTropicalFruit',
        comment = [[(#462) Updating default difficulty setting to Easy.]],
    },
    {
        number = 453,
        date = '2024-03-25',
        author = 'developer',
        comment = [[(#453) Fix Event.add_removable_nth_tick_function]],
    },
    {
        number = 364,
        date = '2024-03-25',
        author = 'DrButtons',
        comment = [[(#364) Small code cleanups, remove legacy/old commands]],
    },
    {
        number = 440,
        date = '2024-03-25',
        author = 'DrButtons',
        comment = [[(#440) move on_player_mined_entity to control-dispatch]],
    },
    {
        number = 452,
        date = '2024-03-22',
        author = 'DrButtons',
        comment = [[(#452) Sync safe group-name with captain group picking]],
    },
    {
        number = 443,
        date = '2024-03-22',
        author = 'cliff_build',
        comment = [[(#443) Add a new tab displaying mutagen values and resource costs]],
    },
    {
        number = 450,
        date = '2024-03-16',
        author = 'cliff_build',
        comment = [[(#450) Small improvements to /calc-send]],
    },
    {
        number = 449,
        date = '2024-03-16',
        author = 'cliff_build',
        comment = [[(#449) Grant infinite-fish-vision when using send-all]],
    },
    {
        number = 451,
        date = '2024-03-15',
        author = 'cliff_build',
        comment = [[(#451) Fix chat messages not showing up in Discord]],
    },
    {
        number = 442,
        date = '2024-03-15',
        author = 'cliff_build',
        comment = [[(#442) Game start time: set it to 0 when something actually happens]],
    },
    {
        number = 437,
        date = '2024-03-15',
        author = 'DrButtons',
        comment = [[(#437) Refactor get_formatted_playtime]],
    },
    {
        number = 439,
        date = '2024-03-14',
        author = 'DrButtons',
        comment = [[(#439) Remove legacy debug code]],
    },
    {
        number = 447,
        date = '2024-03-14',
        author = 'cliff_build',
        comment = [[(#447) Avoid "LuaTile API call when LuaTile was invalid." error]],
    },
    {
        number = 448,
        date = '2024-03-14',
        author = 'cliff_build',
        comment = [[(#448) Automatically clear_cusor when spectating]],
    },
    {
        number = 436,
        date = '2024-03-13',
        author = 'DrButtons',
        comment = [[(#436) fix boss_unit death tracking]],
    },
    {
        number = 438,
        date = '2024-03-13',
        author = 'cliff_build',
        comment = [[(#438) revamp evo/threat calculation, and add /calc-send command]],
    },
    {
        number = 444,
        date = '2024-03-13',
        author = 'DrButtons',
        comment = [[(#444) fix group names that overlap with luaguielement]],
    },
    {
        number = 441,
        date = '2024-03-13',
        author = 'cogito123',
        comment = [[(#441) Allow tag manipulation when frozen]],
    },
    {
        number = 419,
        date = '2024-03-12',
        author = 'cliff_build',
        comment = [[(#419) Refactor/standardize most code that prints out team names]],
    },
    {
        number = 435,
        date = '2024-03-09',
        author = 'Ragnarok77',
        comment = [[(#435) Fix playtime rank]],
    },
    {
        number = 433,
        date = '2024-03-09',
        author = 'cogito123',
        comment = [[(#433) Rework of biter terrain texture to be factorio 2.0 compatible]],
    },
    {
        number = 361,
        date = '2024-03-09',
        author = 'bits-orio',
        comment = [[(#361) Increase the size and edit ratio of mixed patches]],
    },
    {
        number = 383,
        date = '2024-01-04',
        author = 'Ragnarok77',
        comment = [[(#383) New feature : suspend player]],
    },
    {
        number = 406,
        date = '2024-01-04',
        author = 'Ragnarok77',
        comment = [[(#406) Special game : captain event with stats]],
    },
    {
        number = 426,
        date = '2023-12-27',
        author = 'developer',
        comment = [[(#426) fix poll button opens random player camera]],
    },
    {
        number = 422,
        date = '2023-12-20',
        author = 'gsquaredxc',
        comment = [[(#422) Reset game speed to 1 after silo death]],
    },
    {
        number = 401,
        date = '2023-12-20',
        author = 'cogito123',
        comment = [[(#401) perf : Optimize river generation]],
    },
    {
        number = 425,
        date = '2023-12-20',
        author = 'developer',
        comment = [[(#425) fix decontruction on island working on only half of the island]],
    },
    {
        number = 413,
        date = '2023-12-20',
        author = 'developer',
        comment = [[(#413) instant map reset can be done during map reroll + default yes map reroll + added possibility cancel map reroll]],
    },
    {
        number = 421,
        date = '2023-12-20',
        author = 'cliff_build',
        comment = [[(#421) Add comment documenting advantage of sending science in large batches]],
    },
    {
        number = 420,
        date = '2023-12-03',
        author = 'cliff_build',
        comment = [[(#420) Small code simplification in changelog code]],
    },
    {
        number = 331,
        date = '2023-12-03',
        author = 'developer',
        comment = [[(#331) Separate special games into individual files]],
    },
    {
        number = 405,
        date = '2023-11-29',
        author = 'cliff_build',
        comment = [[(#405) Add /spectator-chat command]],
    },
    {
        number = 408,
        date = '2023-11-29',
        author = 'cliff_build',
        comment = [[(#408) Add a spectator-force log message about which team completed a research]],
    },
    {
        number = 417,
        date = '2023-11-27',
        author = 'Ragnarok77',
        comment = [[(#417) Decreased red /green and increased mil/blue science values]],
    },
    {
        number = 412,
        date = '2023-11-27',
        author = 'BigFatDuck',
        comment = [[(#412) fix boss units not traveling with the pack]],
    },
    {
        number = 402,
        date = '2023-11-16',
        author = 'Ragnarok77',
        comment = [[(#402) Bugfix : ignore works now even if different forces or /sth , /nth or /s used]],
    },
    {
        number = 407,
        date = '2023-11-16',
        author = 'Ragnarok77',
        comment = [[(#407) Bugfix : total playtime is now logged]],
    },
    {
        number = 392,
        date = '2023-11-16',
        author = 'Ragnarok77',
        comment = [[(#392) New feature : Add /save-quickbar and /load-quickbar commands]],
    },
    {
        number = 379,
        date = '2023-11-03',
        author = 'DrButtons',
        comment = [[(#379) Add instant map reset command with optional seed argument]],
    },
    {
        number = 391,
        date = '2023-11-03',
        author = 'developer',
        comment = [[(#391) Fix server crash on debug_getinfo with nil handler]],
    },
    {
        number = 395,
        date = '2023-11-03',
        author = 'TheBigZet',
        comment = [[(#395) Remove more unused modules]],
    },
    {
        number = 400,
        date = '2023-10-27',
        author = 'cogito123',
        comment = [[(#400) perf : optim dmg event, refresh delay for healthbar of bosses increased]],
    },
    {
        number = 394,
        date = '2023-10-27',
        author = 'DrButtons',
        comment = [[(#394) perf : Increase refresh threat min delay and optim on code]],
    },
    {
        number = 389,
        date = '2023-10-27',
        author = 'cogito123',
        comment = [[(#389) perf : Biter terrain tiles optimization]],
    },
    {
        number = 382,
        date = '2023-10-27',
        author = 'Ragnarok77',
        comment = [[(#382) Reveal map at start]],
    },
    {
        number = 363,
        date = '2023-10-27',
        author = 'DrButtons',
        comment = [[(#363) Add info.json file]],
    },
    {
        number = 353,
        date = '2023-10-19',
        author = 'developer',
        comment = [[(#353) Special game Mixed ore map]],
    },
    {
        number = 381,
        date = '2023-10-19',
        author = 'BigFatDuck',
        comment = [[(#381) bugfix : NaN propagation in strike code generating desynch]],
    },
    {
        number = 384,
        date = '2023-10-07',
        author = 'Ragnarok77',
        comment = [[(#384) Update changelog script to have it ordered]],
    },
    {
        number = 352,
        date = '2023-10-03',
        author = 'Max1000',
        comment = [[(#352) Introduce map reroll]],
    },
    {
        number = 354,
        date = '2023-10-03',
        author = 'Max1000',
        comment = [[(#354) Special game disable sciences from sending]],
    },
    {
        number = 369,
        date = '2023-09-29',
        author = 'penguinencounter',
        comment = [[(#369) Improved /inventory performance]],
    },
    {
        number = 378,
        date = '2023-07-20',
        author = 'developer',
        comment = [[(#378) Allow change_active_item_group_for_filters for spectators]],
    },
    {
        number = 373,
        date = '2023-07-14',
        author = 'developer',
        comment = [[(#373) Allows group name and description to include spaces and punctuation characters]],
    },
    {
        number = 371,
        date = '2023-07-14',
        author = 'Ragnarok77',
        comment = [[(#371) Set permission selected_tab_changed to true even when frozen so ui not broken anymore for special/groups]],
    },
    {
        number = 362,
        date = '2023-07-13',
        author = 'DrButtons',
        comment = [[(#362) Remove Unused Module and terrain code]],
    },
    {
        number = 374,
        date = '2023-07-13',
        author = 'TheBigZet',
        comment = [[(#374) Clear area of rocks for placing silo's turret pair (redo)]],
    },
    {
        number = 368,
        date = '2023-06-29',
        author = 'gabrielchl',
        comment = [[(#368) feat: add send to server in admin gui]],
    },
    {
        number = 333,
        date = '2023-06-17',
        author = 'Ragnarok77',
        comment = [[(#333) Refined concrete within starting area walls]],
    },
    {
        number = 306,
        date = '2023-06-17',
        author = 'Ragnarok77',
        comment = [[(#306) Bugfix special-events : Prevent bots from placing disabled entities]],
    },
    {
        number = 318,
        date = '2023-05-07',
        author = 'BigFatDuck',
        comment = [[(#318) refactor out existing AI functions cleanly into "Strikes" and "Targets"]],
    },
    {
        number = 356,
        date = '2023-01-29',
        author = 'Max1000',
        comment = [[(#356) fix autounlock uranium ammo after sulfur reaserch]],
    },
    {
        number = 332,
        date = '2023-01-27',
        author = 'Ragnarok77',
        comment = [[(#332) Special event shared evo and throws]],
    },
    {
        number = 339,
        date = '2023-01-26',
        author = 'Ragnarok77',
        comment = [[(#339) Bugfix to avoid spam of error in log when decon]],
    },
    {
        number = 351,
        date = '2023-01-26',
        author = 'voski',
        comment = [[(#351) Do not allow players to create a new group with the name of an existing group]],
    },
    {
        number = 347,
        date = '2023-01-26',
        author = 'gabrielchl',
        comment = [[(#347) feat(gui): show game speed next to game time]],
    },
    {
        number = 338,
        date = '2023-01-26',
        author = 'Max1000',
        comment = [[(#338) fix team name on biters spotted]],
    },
    {
        number = 336,
        date = '2023-01-26',
        author = 'Max1000',
        comment = [[(#336) difficulty_vote: prevent voting same difficulty.]],
    },
    {
        number = 334,
        date = '2022-12-18',
        author = 'developer',
        comment = [[(#334) Change river function]],
    },
    {
        number = 335,
        date = '2022-12-18',
        author = 'developer',
        comment = [[(#335) Add New Year Island decorations]],
    },
    {
        number = 330,
        date = '2022-12-18',
        author = 'developer',
        comment = [[(#330) Fix Limited lives desync]],
    },
    {
        number = 304,
        date = '2022-12-18',
        author = 'developer',
        comment = [[(#304) Perf: Improve river check function]],
    },
    {
        number = 329,
        date = '2022-11-22',
        author = 'TheBigZet',
        comment = [[(#329) Replaced element_style() with gui_style()]],
    },
    {
        number = 300,
        date = '2022-11-22',
        author = 'Ragnarok77',
        comment = [[(#300) New feature : show amount of votes of diff in gui]],
    },
    {
        number = 327,
        date = '2022-11-22',
        author = 'developer',
        comment = [[(#327) Special game: Limited lives]],
    },
    {
        number = 290,
        date = '2022-11-18',
        author = 'TheBigZet',
        comment = [[(#290) Enable profiler]],
    },
    {
        number = 276,
        date = '2022-10-25',
        author = 'Ragnarok77',
        comment = [[(#276) French translation of welcome message]],
    },
    {
        number = 322,
        date = '2022-09-12',
        author = 'TheBigZet',
        comment = [[(#322) Develop to master]],
    },
    {
        number = 321,
        date = '2022-09-11',
        author = 'TheBigZet',
        comment = [[(#321) Dev backport]],
    },
    {
        number = 292,
        date = '2022-09-11',
        author = 'Ragnarok77',
        comment = [[(#292) Fix threat boss issue going negative too often (waves were oversized) and frozen boss bug and added boss announce]],
    },
    {
        number = 288,
        date = '2022-08-27',
        author = 'TheBigZet',
        comment = [[(#288) New histories]],
    },
    {
        number = 303,
        date = '2022-08-06',
        author = 'TheBigZet',
        comment = [[(#303) Added path to errors from event_core]],
    },
    {
        number = 301,
        date = '2022-08-06',
        author = 'Ragnarok77',
        comment = [[(#301) Show big threat value with k or m at end of text]],
    },
    {
        number = 302,
        date = '2022-08-06',
        author = 'TheBigZet',
        comment = [[(#302) Enabled editor and config in spectator]],
    },
    {
        number = 298,
        date = '2022-08-05',
        author = 'developer',
        comment = [[(#298) Fix spectator in vehicle]],
    },
    {
        number = 297,
        date = '2022-08-05',
        author = 'developer',
        comment = [[(#297) Fix ghost rotation by spectator]],
    },
    {
        number = 299,
        date = '2022-08-05',
        author = 'Ragnarok77',
        comment = [[(#299) Ura ammo and kovarex researched when ura processing is researched, same for gate with wall]],
    },
    {
        number = 278,
        date = '2022-07-30',
        author = 'Ragnarok77',
        comment = [[(#278) Prevent pathfinder crossing river(made by developer, not Ragnarok77)]],
    },
    {
        number = 282,
        date = '2022-07-30',
        author = 'AwesomePatrol',
        comment = [[(#282) perf: Small improvements to biter reanimation logic]],
    },
    {
        number = 295,
        date = '2022-07-30',
        author = 'TheBigZet',
        comment = [[(#295) Disabled polls]],
    },
    {
        number = 281,
        date = '2022-06-25',
        author = 'Ragnarok77',
        comment = [[(#281) Perf : No find entities used when defense are built are far from nest]],
    },
    {
        number = 259,
        date = '2022-06-25',
        author = 'TheBigZet',
        comment = [[(#259) Added mixed send functionality]],
    },
    {
        number = 248,
        date = '2022-06-25',
        author = 'Ragnarok77',
        comment = [[(#248) Anti afk system]],
    },
    {
        number = 247,
        date = '2022-06-25',
        author = 'Ragnarok77',
        comment = [[(#247) Global speaker won't nuke speakers in jail and jail speaker heard by all forces]],
    },
    {
        number = 279,
        date = '2022-06-09',
        author = 'Ragnarok77',
        comment = [[(#279) Implementation of boss]],
    },
    {
        number = 291,
        date = '2022-06-09',
        author = 'mysticamber',
        comment = [[(#291) Backport]],
    },
    {
        number = 287,
        date = '2022-05-31',
        author = 'Ragnarok77',
        comment = [[(#287) added launch silo sentence in welcome message]],
    },
    {
        number = 286,
        date = '2022-05-31',
        author = 'mysticamber',
        comment = [[(#286) Dev backport]],
    },
    {
        number = 283,
        date = '2022-05-31',
        author = 'Ragnarok77',
        comment = [[(#283) Increase ura frequency by 10%, copper frequency by 15%]],
    },
    {
        number = 280,
        date = '2022-05-31',
        author = 'Ragnarok77',
        comment = [[(#280) Added uranium ammo research researched by default]],
    },
    {
        number = 241,
        date = '2022-05-15',
        author = 'Ragnarok77',
        comment = [[(#241) Fix messing research queue exploit in jail]],
    },
    {
        number = 273,
        date = '2022-05-15',
        author = 'TheBigZet',
        comment = [[(#273) Special games gui tweaks]],
    },
    {
        number = 268,
        date = '2022-05-15',
        author = 'TheBigZet',
        comment = [[(#268) Removed auto research of silo]],
    },
    {
        number = 267,
        date = '2022-05-15',
        author = 'TheBigZet',
        comment = [[(#267) Disabled manual rocket launch]],
    },
    {
        number = 274,
        date = '2022-05-15',
        author = 'Ragnarok77',
        comment = [[(#274) Fixed exploit landfill enemy side and no decon on enemy side]],
    },
    {
        number = 272,
        date = '2022-05-12',
        author = 'TheBigZet',
        comment = [[(#272) Changed yellow sci mutagen from 1200 to 1600]],
    },
    {
        number = 269,
        date = '2022-05-06',
        author = 'TheBigZet',
        comment = [[(#269) Revert "Admin panel redo"]],
    },
    {
        number = 257,
        date = '2022-04-30',
        author = 'TheBigZet',
        comment = [[(#257) Admin panel redo]],
    },
    {
        number = 266,
        date = '2022-04-22',
        author = 'mysticamber',
        comment = [[(#266) Welcome message]],
    },
    {
        number = 263,
        date = '2022-04-20',
        author = 'TheBigZet',
        comment = [[(#263) Special game disabled research]],
    },
    {
        number = 265,
        date = '2022-04-20',
        author = 'TheBigZet',
        comment = [[(#265) Added auto-shouting after game ending]],
    },
    {
        number = 264,
        date = '2022-04-20',
        author = 'TheBigZet',
        comment = [[(#264) Changed jail_song variables to local]],
    },
    {
        number = 262,
        date = '2022-04-20',
        author = 'TheBigZet',
        comment = [[(#262) Special game: Disabled entities]],
    },
    {
        number = 253,
        date = '2022-04-13',
        author = 'Ragnarok77',
        comment = [[(#253) Fix an exploit with landfill]],
    },
    {
        number = 258,
        date = '2022-04-13',
        author = 'gsquaredxc',
        comment = [[(#258) Change GitHub link to this GitHub]],
    },
    {
        number = 261,
        date = '2022-04-13',
        author = 'TheBigZet',
        comment = [[(#261) Fixed double printing shouts for admins]],
    },
    {
        number = 255,
        date = '2022-02-01',
        author = 'developer',
        comment = [[(#255) Revert "Add holiday decorations to the island"]],
    },
    {
        number = 244,
        date = '2021-12-28',
        author = 'Ragnarok77',
        comment = [[(#244) Cancel crafting queue when going to spectate]],
    },
    {
        number = 250,
        date = '2021-12-28',
        author = 'Ragnarok77',
        comment = [[(#250) Renamed autotag to just East or West for shorter name instead]],
    },
    {
        number = 246,
        date = '2021-12-25',
        author = 'uneuro',
        comment = [[(#246) holidays]],
    },
    {
        number = 245,
        date = '2021-12-25',
        author = 'Ragnarok77',
        comment = [[(#245) Create troll song at map init in jail]],
    },
    {
        number = 243,
        date = '2021-12-25',
        author = 'developer',
        comment = [[(#243) Add holiday decorations to the island]],
    },
    {
        number = 240,
        date = '2021-12-19',
        author = 'developer',
        comment = [[(#240) Mirror decoratives to south]],
    },
    {
        number = 239,
        date = '2021-12-17',
        author = 'Ragnarok77',
        comment = [[(#239) Auto tagging outpost]],
    },
    {
        number = 235,
        date = '2021-12-15',
        author = 'Ragnarok77',
        comment = [[(#235) Increased copper and stone size by 10%]],
    },
    {
        number = 232,
        date = '2021-12-15',
        author = 'Ragnarok77',
        comment = [[(#232) Add changelog tab]],
    },
    {
        number = 236,
        date = '2021-12-15',
        author = 'AwesomePatrol',
        comment = [[(#236) Set path_finder settings]],
    },
    {
        number = 237,
        date = '2021-12-15',
        author = 'AwesomePatrol',
        comment = [[(#237) Add more threat to compensate revive]],
    },
    {
        number = 238,
        date = '2021-12-15',
        author = 'AwesomePatrol',
        comment = [[(#238) Clear clipboard on game join]],
    },
    {
        number = 231,
        date = '2021-12-12',
        author = 'Ragnarok77',
        comment = [[(#231) Update/prevent landfilling by untrusted user]],
    },
    {
        number = 227,
        date = '2021-12-12',
        author = 'Ragnarok77',
        comment = [[(#227) Removed trust check on clear-corpses command]],
    },
    {
        number = 234,
        date = '2021-12-12',
        author = 'Ragnarok77',
        comment = [[(#234) Fix silo grief (mirroring)]],
    },
    {
        number = 221,
        date = '2021-12-09',
        author = 'DrButtons',
        comment = [[(#221) fix antigrief inconsistency]],
    },
    {
        number = 228,
        date = '2021-12-09',
        author = 'Ragnarok77',
        comment = [[(#228) Limited threshold of biters reviving to 90% chance]],
    },
    {
        number = 230,
        date = '2021-12-09',
        author = 'developer',
        comment = [[(#230) Do not allow ghosts on enemy side]],
    },
    {
        number = 225,
        date = '2021-12-09',
        author = 'AwesomePatrol',
        comment = [[(#225) Fix difficulty GUI lag spikes]],
    },
    {
        number = 226,
        date = '2021-12-09',
        author = 'Ragnarok77',
        comment = [[(#226) Added infinite spy when white science is thrown]],
    },
    {
        number = 211,
        date = '2021-12-06',
        author = 'TheBigZet',
        comment = [[(#211) Added special_games system]],
    },
    {
        number = 222,
        date = '2021-12-06',
        author = 'AwesomePatrol',
        comment = [[(#222) Improve biter performance]],
    },
    {
        number = 205,
        date = '2021-11-25',
        author = 'developer',
        comment = [[(#205) Remove vehicle from silo]],
    },
    {
        number = 208,
        date = '2021-11-21',
        author = 'TheBigZet',
        comment = [[(#208) Ban improvements]],
    },
    {
        number = 203,
        date = '2021-11-21',
        author = 'TheBigZet',
        comment = [[(#203) First join gui minor tweaks]],
    },
    {
        number = 214,
        date = '2021-11-19',
        author = 'TheBigZet',
        comment = [[(#214) Quick and dirty way to fix desync]],
    },
    {
        number = 209,
        date = '2021-11-10',
        author = 'Tomab',
        comment = [[(#209) Improved readme]],
    },
    {
        number = 210,
        date = '2021-11-08',
        author = 'Tomab',
        comment = [[(#210) Change text warning to accurately reflect mechanics]],
    },
    {
        number = 206,
        date = '2021-10-30',
        author = 'mysticamber',
        comment = [[(#206) shout-fix: fix shout logging so that non admin shouts get logged too]],
    },
    {
        number = 207,
        date = '2021-10-30',
        author = 'mysticamber',
        comment = [[(#207) mutes - make mute great again]],
    },
    {
        number = 201,
        date = '2021-10-11',
        author = 'TheBigZet',
        comment = [[(#201) Top gui visual cleanup]],
    },
    {
        number = 202,
        date = '2021-10-11',
        author = 'TheBigZet',
        comment = [[(#202) Add join_random_button]],
    },
    {
        number = 198,
        date = '2021-09-19',
        author = 'gabrielchl',
        comment = [[(#198) Print msg to admin upon offshore pump mining]],
    },
    {
        number = 199,
        date = '2021-09-19',
        author = 'mysticamber',
        comment = [[(#199) spying-fix: if you've chosen a team, remove space sci button]],
    },
    {
        number = 195,
        date = '2021-09-14',
        author = 'mysticamber',
        comment = [[(#195) discord-log-shout: log shout messages to discord]],
    },
    {
        number = 196,
        date = '2021-08-31',
        author = 'mysticamber',
        comment = [[(#196) we-survivor: automate sending ppl to spec. Make the delay to return to team configurable]],
    },
    {
        number = 185,
        date = '2021-08-13',
        author = 'AwesomePatrol',
        comment = [[(#185) Fix evo reset when admins change difficulty]],
    },
    {
        number = 186,
        date = '2021-08-13',
        author = 'mysticamber',
        comment = [[(#186) Add comment to clear_copy_history]],
    },
    {
        number = 184,
        date = '2021-07-24',
        author = 'mysticamber',
        comment = [[(#184) clear-bp-history: overwrite copy history with miner]],
    },
    {
        number = 183,
        date = '2021-07-18',
        author = 'mysticamber',
        comment = [[(#183) inverse-game: disable friendly_fire]],
    },
    {
        number = 182,
        date = '2021-07-17',
        author = 'mysticamber',
        comment = [[(#182) inverse-game]],
    },
    {
        number = 181,
        date = '2021-06-27',
        author = 'mysticamber',
        comment = [[(#181) Pixie dust]],
    },
    {
        number = 180,
        date = '2021-06-20',
        author = 'cogito123',
        comment = [[(#180) Remove all turrets from target pool]],
    },
    {
        number = 178,
        date = '2021-06-16',
        author = 'cogito123',
        comment = [[(#178) Fix truncated ores around spawn area]],
    },
    {
        number = 176,
        date = '2021-06-08',
        author = 'cogito123',
        comment = [[(#176) Add support for configurable spawn area ore patches]],
    },
    {
        number = 160,
        date = '2021-06-08',
        author = 'AwesomePatrol',
        comment = [[(#160) 2nd attempt at increasing difficulty]],
    },
    {
        number = 170,
        date = '2021-06-05',
        author = 'cogito123',
        comment = [[(#170) Rework unit reanimation system]],
    },
    {
        number = 168,
        date = '2021-05-23',
        author = 'uneuro',
        comment = [[(#168) Revert "few commands for WE. no need revert after event end. (i think so :D )"]],
    },
    {
        number = 167,
        date = '2021-05-23',
        author = 'ghost',
        comment = [[(#167) few commands for WE. no need revert after event end. (i think so :D )]],
    },
    {
        number = 166,
        date = '2021-05-23',
        author = 'cogito123',
        comment = [[(#166) Biters bugfixes]],
    },
    {
        number = 165,
        date = '2021-05-22',
        author = 'cogito123',
        comment = [[(#165) Remove additional teleport during game over phase]],
    },
    {
        number = 164,
        date = '2021-05-20',
        author = 'cogito123',
        comment = [[(#164) Force chunk replication into lockstep]],
    },
    {
        number = 163,
        date = '2021-05-17',
        author = 'cogito123',
        comment = [[(#163) Improvement to map generation performance]],
    },
    {
        number = 161,
        date = '2021-05-15',
        author = 'AwesomePatrol',
        comment = [[(#161) Always use a standard team name in post-game discord message (and more QoL stuff)]],
    },
    {
        number = 162,
        date = '2021-05-15',
        author = 'AwesomePatrol',
        comment = [[(#162) Add two wood to inventory like in vanilla]],
    },
    {
        number = 158,
        date = '2021-05-09',
        author = 'uneuro',
        comment = [[(#158) More improvements 1]],
    },
    {
        number = 155,
        date = '2021-05-09',
        author = 'Hornwitser',
        comment = [[(#155) Revert #140]],
    },
    {
        number = 156,
        date = '2021-05-09',
        author = 'uneuro',
        comment = [[(#156) Laser and mutagen suggestions]],
    },
    {
        number = 154,
        date = '2021-05-01',
        author = 'derkachdaniil',
        comment = [[(#154) Update feeding.lua - buff endgame biters]],
    },
    {
        number = 153,
        date = '2021-04-26',
        author = 'uneuro',
        comment = [[(#153) Balance update 1]],
    },
    {
        number = 150,
        date = '2021-04-24',
        author = 'ghost',
        comment = [[(#150) fix revive biters]],
    },
    {
        number = 151,
        date = '2021-04-24',
        author = 'AwesomePatrol',
        comment = [[(#151) Fix revive buff not applying]],
    },
    {
        number = 149,
        date = '2021-03-23',
        author = 'mysticamber',
        comment = [[(#149) update-discord-link: update chatbot.lua with correct discord link,]],
    },
    {
        number = 148,
        date = '2021-03-23',
        author = 'mysticamber',
        comment = [[(#148) update-discord-link: free biter battles]],
    },
    {
        number = 145,
        date = '2021-03-18',
        author = 'kajendra',
        comment = [[(#145) Revert "Revert "Disabled mines temporarily until better fix is found""]],
    },
    {
        number = 144,
        date = '2021-03-16',
        author = 'kajendra',
        comment = [[(#144) Revert "Disabled mines temporarily until better fix is found"]],
    },
    {
        number = 142,
        date = '2021-03-15',
        author = 'guppyfaced',
        comment = [[(#142) Revert "Difficulty voting by average"]],
    },
    {
        number = 141,
        date = '2021-03-15',
        author = 'guppyfaced',
        comment = [[(#141) Fix ai pathfinding v2]],
    },
    {
        number = 139,
        date = '2021-03-15',
        author = 'St4telyRaven',
        comment = [[(#139) flamer upgrades buff]],
    },
    {
        number = 140,
        date = '2021-03-15',
        author = 'derkachdaniil',
        comment = [[(#140) Limit mines]],
    },
    {
        number = 138,
        date = '2021-03-15',
        author = 'guymaor86',
        comment = [[(#138) Difficulty voting by average]],
    },
    {
        number = 137,
        date = '2021-03-14',
        author = 'St4telyRaven',
        comment = [[(#137) fix difficulty reversion glitch for 480 min games]],
    },
    {
        number = 136,
        date = '2021-03-12',
        author = 'St4telyRaven',
        comment = [[(#136) stone copper buff]],
    },
    {
        number = 77,
        date = '2021-03-12',
        author = 'mysticamber',
        comment = [[(#77) DashCee: Reducing DashCee's PR. Removing unused maps]],
    },
    {
        number = 135,
        date = '2021-03-07',
        author = 'St4telyRaven',
        comment = [[(#135) Laser Buff]],
    },
    {
        number = 103,
        date = '2021-03-07',
        author = 'derkachdaniil',
        comment = [[(#103) changeable projectile_damage_upgrade]],
    },
    {
        number = 120,
        date = '2021-03-07',
        author = 'derkachdaniil',
        comment = [[(#120) damage updates customizable]],
    },
    {
        number = 126,
        date = '2021-03-06',
        author = 'kajendra',
        comment = [[(#126) Disabled mines temporarily until better fix is found]],
    },
    {
        number = 134,
        date = '2021-03-06',
        author = 'St4telyRaven',
        comment = [[(#134) Reduced Voting Options]],
    },
    {
        number = 133,
        date = '2021-03-06',
        author = 'St4telyRaven',
        comment = [[(#133) Update Peace Periods (slower increase)]],
    },
    {
        number = 132,
        date = '2021-03-06',
        author = 'St4telyRaven',
        comment = [[(#132) Add Peace Periods]],
    },
    {
        number = 131,
        date = '2021-03-06',
        author = 'St4telyRaven',
        comment = [[(#131) Reduced Difficulty for Choices below Normal]],
    },
    {
        number = 128,
        date = '2021-03-06',
        author = 'St4telyRaven',
        comment = [[(#128) Update ai.lua]],
    },
    {
        number = 129,
        date = '2021-03-06',
        author = 'St4telyRaven',
        comment = [[(#129) Disabled Science Feeding before Voting Ends]],
    },
    {
        number = 130,
        date = '2021-03-06',
        author = 'St4telyRaven',
        comment = [[(#130) Update difficulty_vote.lua ????]],
    },
    {
        number = 106,
        date = '2021-03-01',
        author = 'kajendra',
        comment = [[(#106) Updated Readme to include TOC and new URL to git repo]],
    },
    {
        number = 124,
        date = '2021-02-26',
        author = 'kajendra',
        comment = [[(#124) Fixed a bug that displays the seconds as a decimal]],
    },
    {
        number = 127,
        date = '2021-02-26',
        author = 'guymaor86',
        comment = [[(#127) Revert "Improve biter pathfinding"]],
    },
    {
        number = 123,
        date = '2021-02-25',
        author = 'AwesomePatrol',
        comment = [[(#123) Improve biter pathfinding]],
    },
    {
        number = 125,
        date = '2021-02-17',
        author = 'mysticamber',
        comment = [[(#125) torunament-feb21: removing free silo]],
    },
    {
        number = 96,
        date = '2021-01-26',
        author = 'AwesomePatrol',
        comment = [[(#96) Fix lag in long games]],
    },
    {
        number = 107,
        date = '2021-01-25',
        author = 'kajendra',
        comment = [[(#107) Updated endgame message upon Raven's request]],
    },
    {
        number = 109,
        date = '2021-01-25',
        author = 'St4telyRaven',
        comment = [[(#109) Update tables.lua]],
    },
    {
        number = 116,
        date = '2021-01-25',
        author = 'St4telyRaven',
        comment = [[(#116) Update init.lua]],
    },
    {
        number = 115,
        date = '2021-01-25',
        author = 'St4telyRaven',
        comment = [[(#115) Removed update_difficulty() in ai.lua]],
    },
    {
        number = 114,
        date = '2021-01-25',
        author = 'St4telyRaven',
        comment = [[(#114) Revert Blocking Science Sent before Voting Ends]],
    },
    {
        number = 112,
        date = '2021-01-25',
        author = 'St4telyRaven',
        comment = [[(#112) Update init.lua]],
    },
    {
        number = 111,
        date = '2021-01-25',
        author = 'St4telyRaven',
        comment = [[(#111) Update ai.lua]],
    },
    {
        number = 110,
        date = '2021-01-25',
        author = 'St4telyRaven',
        comment = [[(#110) Update main.lua]],
    },
    {
        number = 104,
        date = '2021-01-23',
        author = 'derkachdaniil',
        comment = [[(#104) Fix mines]],
    },
    {
        number = 101,
        date = '2021-01-18',
        author = 'guymaor86',
        comment = [[(#101) Update PR template]],
    },
    {
        number = 100,
        date = '2021-01-17',
        author = 'AwesomePatrol',
        comment = [[(#100) Fixup silo research changes]],
    },
    {
        number = 95,
        date = '2021-01-16',
        author = 'St4telyRaven',
        comment = [[(#95) Revert "Update tables.lua"]],
    },
    {
        number = 94,
        date = '2021-01-16',
        author = 'St4telyRaven',
        comment = [[(#94) Revert "Update tables.lua"]],
    },
    {
        number = 93,
        date = '2021-01-16',
        author = 'St4telyRaven',
        comment = [[(#93) Revert "Update tables.lua"]],
    },
    {
        number = 92,
        date = '2021-01-16',
        author = 'St4telyRaven',
        comment = [[(#92) Revert "Update tables.lua"]],
    },
    {
        number = 83,
        date = '2021-01-16',
        author = 'kajendra',
        comment = [[(#83) Chat cmd updates]],
    },
    {
        number = 81,
        date = '2021-01-15',
        author = 'mysticamber',
        comment = [[(#81) Additional commands]],
    },
    {
        number = 82,
        date = '2021-01-15',
        author = 'guymaor86',
        comment = [[(#82) tournament mode - admin can send message as a spectator]],
    },
    {
        number = 85,
        date = '2021-01-15',
        author = 'ghost',
        comment = [[(#85) vote fix. now will round to higher difficulty.]],
    },
    {
        number = 87,
        date = '2021-01-15',
        author = 'kajendra',
        comment = [[(#87) Added 10 burner miner drills when player spawns]],
    },
    {
        number = 88,
        date = '2021-01-15',
        author = 'guymaor86',
        comment = [[(#88) Added 2 turrets around silo]],
    },
    {
        number = 89,
        date = '2021-01-15',
        author = 'AwesomePatrol',
        comment = [[(#89) Refactor free silo]],
    },
    {
        number = 91,
        date = '2021-01-15',
        author = 'St4telyRaven',
        comment = [[(#91) Update tables.lua]],
    },
    {
        number = 90,
        date = '2021-01-15',
        author = 'St4telyRaven',
        comment = [[(#90) Update tables.lua]],
    },
    {
        number = 80,
        date = '2021-01-13',
        author = 'mysticamber',
        comment = [[(#80) difficulty-votes: clear vote table on revote]],
    },
    {
        number = 86,
        date = '2021-01-13',
        author = 'St4telyRaven',
        comment = [[(#86) Update tables.lua]],
    },
    {
        number = 84,
        date = '2021-01-12',
        author = 'St4telyRaven',
        comment = [[(#84) Update tables.lua]],
    },
    {
        number = 79,
        date = '2021-01-11',
        author = 'kajendra',
        comment = [[(#79) Notifies both teams when a new level of biter spawns]],
    },
    {
        number = 75,
        date = '2021-01-11',
        author = 'kajendra',
        comment = [[(#75) Added options to send more fish at a time, updated tooltip]],
    },
    {
        number = 72,
        date = '2020-12-29',
        author = 'thePiedPiper13',
        comment = [[(#72) Updated discord link to never expire and put at top of info]],
    },
    {
        number = 69,
        date = '2020-12-27',
        author = 'mysticamber',
        comment = [[(#69) Centralize ammo modifier values]],
    },
    {
        number = 70,
        date = '2020-12-27',
        author = 'kajendra',
        comment = [[(#70) Fixed typos & unused variables]],
    },
    {
        number = 68,
        date = '2020-12-27',
        author = 'kajendra',
        comment = [[(#68) Updated Readme File with formatting, added Testing Instructions & modified text on PR's]],
    },
    {
        number = 67,
        date = '2020-12-27',
        author = 'guymaor86',
        comment = [[(#67) Pull request template]],
    },
    {
        number = 64,
        date = '2020-12-27',
        author = 'St4telyRaven',
        comment = [[(#64) Update init.lua]],
    },
    {
        number = 74,
        date = '2020-12-27',
        author = 'mysticamber',
        comment = [[(#74) Prevent bots from tiling]],
    },
    {
        number = 58,
        date = '2020-12-22',
        author = 'mysticamber',
        comment = [[(#58) Difficulty vote commands]],
    },
    {
        number = 61,
        date = '2020-12-22',
        author = 'St4telyRaven',
        comment = [[(#61) Update init.lua]],
    },
    {
        number = 60,
        date = '2020-12-22',
        author = 'St4telyRaven',
        comment = [[(#60) Update difficulty_vote.lua]],
    },
    {
        number = 59,
        date = '2020-12-22',
        author = 'St4telyRaven',
        comment = [[(#59) Update tables.lua]],
    },
    {
        number = 57,
        date = '2020-12-22',
        author = 'St4telyRaven',
        comment = [[(#57) Update difficulty_vote.lua]],
    },
    {
        number = 56,
        date = '2020-12-21',
        author = 'mysticamber',
        comment = [[(#56) issue-36: chatbot - on_console_chat - remove get server time as it causes problems]],
    },
    {
        number = 55,
        date = '2020-12-20',
        author = 'St4telyRaven',
        comment = [[(#55) Update ai.lua]],
    },
    {
        number = 54,
        date = '2020-12-20',
        author = 'uneuro',
        comment = [[(#54) put back normal values for nades]],
    },
    {
        number = 51,
        date = '2020-12-20',
        author = 'mysticamber',
        comment = [[(#51) bb: adding evo threat and player list to end of game messages]],
    },
    {
        number = 52,
        date = '2020-12-20',
        author = 'guymaor86',
        comment = [[(#52) Make river wider against rocket launchers]],
    },
    {
        number = 50,
        date = '2020-12-18',
        author = 'St4telyRaven',
        comment = [[(#50) Update tables.lua]],
    },
    {
        number = 49,
        date = '2020-12-17',
        author = 'mysticamber',
        comment = [[(#49) biter battle: send chat to discord even during tournament]],
    },
    {
        number = 48,
        date = '2020-12-17',
        author = 'guymaor86',
        comment = [[(#48) mirror map-not mirror reverse]],
    },
    {
        number = 44,
        date = '2020-12-17',
        author = 'mysticamber',
        comment = [[(#44) biter-battles: mvp stats only get sent once]],
    },
    {
        number = 47,
        date = '2020-12-17',
        author = 'guymaor86',
        comment = [[(#47) New guide in readme]],
    },
    {
        number = 42,
        date = '2020-12-15',
        author = 'uneuro',
        comment = [[(#42) add mysticamber link for discord bot]],
    },
    {
        number = 41,
        date = '2020-12-14',
        author = 'St4telyRaven',
        comment = [[(#41) Update init.lua]],
    },
    {
        number = 34,
        date = '2020-12-14',
        author = 'DashCee',
        comment = [[(#34) File text updates]],
    },
    {
        number = 24,
        date = '2020-12-11',
        author = 'mysticamber',
        comment = [[(#24) biter-battles: adding north-chat and south-chat commands]],
    },
    {
        number = 23,
        date = '2020-12-11',
        author = 'mysticamber',
        comment = [[(#23) Contributing to repo]],
    },
    {
        number = 22,
        date = '2020-12-11',
        author = 'thePiedPiper13',
        comment = [[(#22) Updated Biter battles map info (?) description to include 2 guides and the discord server links]],
    },
    {
        number = 20,
        date = '2020-12-10',
        author = 'DashCee',
        comment = [[(#20) Updating readme]],
    },
    {
        number = 19,
        date = '2020-12-10',
        author = 'uneuro',
        comment = [[(#19) default bbv2]],
    },
    {
        number = 18,
        date = '2020-12-10',
        author = 'uneuro',
        comment = [[(#18) Update control.lua]],
    },
    {
        number = 14,
        date = '2020-12-10',
        author = 'DashCee',
        comment = [[(#14) Updating the oil yield value from 0.27 to 0.5.]],
    },
    {
        number = 13,
        date = '2020-12-10',
        author = 'thePiedPiper13',
        comment = [[(#13) Update init.lua]],
    },
    {
        number = 17,
        date = '2020-12-10',
        author = 'ghost',
        comment = [[(#17) change vote system from average to median]],
    },
    {
        number = 16,
        date = '2020-12-10',
        author = 'DashCee',
        comment = [[(#16) Compress difficulty values upwards]],
    },
    {
        number = 10,
        date = '2020-12-10',
        author = 'mysticamber',
        comment = [[(#10) mixed ore patches: adding multiplier]],
    },
    {
        number = 11,
        date = '2020-12-10',
        author = 'mysticamber',
        comment = [[(#11) Chat]],
    },
    {
        number = 12,
        date = '2020-12-10',
        author = 'mysticamber',
        comment = [[(#12) biter-battles: adding option to only send msg to a specific team as a spectator]],
    },
    {
        number = 9,
        date = '2020-12-07',
        author = 'mysticamber',
        comment = [[(#9) biter-battles: difficulty vote - removing hard coded 7 in difficulties]],
    },
    {
        number = 8,
        date = '2020-11-28',
        author = 'St4telyRaven',
        comment = [[(#8) Update init.lua]],
    },
    {
        number = 7,
        date = '2020-11-28',
        author = 'St4telyRaven',
        comment = [[(#7) Update terrain.lua]],
    },
    {
        number = 6,
        date = '2020-11-28',
        author = 'St4telyRaven',
        comment = [[(#6) Update difficulty_vote.lua]],
    },
    {
        number = 2,
        date = '2020-11-28',
        author = 'St4telyRaven',
        comment = [[(#2) Update main.lua]],
    },
    {
        number = 3,
        date = '2020-11-28',
        author = 'St4telyRaven',
        comment = [[(#3) Update init.lua]],
    },
    {
        number = 4,
        date = '2020-11-27',
        author = 'St4telyRaven',
        comment = [[(#4) Update functions.lua]],
    },
    {
        number = 5,
        date = '2020-11-27',
        author = 'St4telyRaven',
        comment = [[(#5) Update tables.lua]],
    },
    {
        number = 1,
        date = '2020-11-27',
        author = 'St4telyRaven',
        comment = [[(#1) Update ai.lua]],
    },
}
