name: Fix Lint With Stylua
on:
  push:
    paths:
      - "**.lua"
  pull_request:
    paths:
      - "**.lua"
jobs:
  check_code_format:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: .
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Fix StyLua
